/** Tailwind config — all colours are semantic CSS variables (see src/styles/tokens.css, generated by scripts/gen-tokens.mjs).
 *  Use logical utilities only (ms-/me-/ps-/pe-/start-/end-/text-start/border-s/rounded-s) so the layout is RTL-correct. */
const c = (name) => `rgb(var(--c-${name}) / <alpha-value>)`

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: c('bg'),
        surface: c('surface'),
        'surface-2': c('surface-2'),
        'surface-3': c('surface-3'),
        line: c('line'),
        'line-strong': c('line-strong'),
        fg: c('fg'),
        muted: c('muted'),
        subtle: c('subtle'),
        primary: c('primary'),
        'primary-hover': c('primary-hover'),
        'primary-soft': c('primary-soft'),
        'on-primary': c('on-primary'),
        success: c('success'),
        'success-soft': c('success-soft'),
        warning: c('warning'),
        'warning-soft': c('warning-soft'),
        danger: c('danger'),
        'danger-soft': c('danger-soft'),
        info: c('info'),
        accent: c('accent'),
        'accent-soft': c('accent-soft'),
        'info-soft': c('info-soft'),
        'risk-low': c('success'),
        'risk-medium': c('warning'),
        'risk-high': c('danger'),
      },
      fontFamily: {
        sans: ['Vazirmatn', 'Tahoma', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      borderRadius: {
        sm: 'var(--r-sm)',
        DEFAULT: 'var(--r-md)',
        md: 'var(--r-md)',
        lg: 'var(--r-lg)',
        xl: 'var(--r-xl)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        pop: 'var(--shadow-pop)',
      },
      maxWidth: { page: '72rem' },
      keyframes: {
        shimmer: { '100%': { transform: 'translateX(-100%)' } },
        'sheet-up': { from: { transform: 'translateY(100%)' }, to: { transform: 'translateY(0)' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'pop-in': { from: { opacity: '0', transform: 'scale(.96)' }, to: { opacity: '1', transform: 'scale(1)' } },
      },
      animation: {
        shimmer: 'shimmer 1.6s infinite',
        'sheet-up': 'sheet-up .22s ease-out',
        'fade-in': 'fade-in .18s ease-out',
        'pop-in': 'pop-in .16s ease-out',
      },
    },
  },
  plugins: [],
}
