# -*- coding: utf-8 -*-
"""Copy part 4: notification templates. Channel suffixes: inapp.title/inapp.body, msg (Telegram AND Bale plain text), sms, email.subject/email.body.
Rules: never include card numbers, CVV, voucher codes, OTP (except the OTP SMS itself) or passwords; every message names {brand}
only where useful; SMS <= 2 UCS-2 segments (OTP <= 1); links are always {url} (short domain, no tracking)."""
COPY = {
# ── auth / security ──
"notif.auth.otp.sms": "کد تأیید {brand}: {code}\nاعتبار: {time}\nاین کد را به کسی ندهید.\n@{domain} #{code}",
"notif.auth.otp.msg": "کد تأیید شما: {code}\nاعتبار: {time}. این کد را به کسی ندهید.",
"notif.account.welcome.inapp.title": "به {brand} خوش آمدید",
"notif.account.welcome.inapp.body": "حساب شما ساخته شد. از بخش محصولات اولین سفارش خود را ثبت کنید.",
"notif.account.welcome.msg": "به {brand} خوش آمدید.\nحساب شما ساخته شد و از همین‌جا می‌توانید سفارش دهید و آن را پیگیری کنید.",
"notif.security.newLogin.inapp.title": "ورود تازه به حساب",
"notif.security.newLogin.inapp.body": "ورود از دستگاه جدید در {time}. اگر شما نبودید، فوراً از همه‌ی دستگاه‌ها خارج شوید.",
"notif.security.newLogin.msg": "ورود تازه به حساب شما در {time} ثبت شد.\nاگر شما نبودید، از بخش «حساب من» از همه‌ی دستگاه‌ها خارج شوید یا به پشتیبانی پیام دهید.",
"notif.security.newLogin.sms": "{brand}: ورود تازه به حساب شما. اگر شما نبودید با پشتیبانی تماس بگیرید.",
"notif.security.reveal.inapp.title": "اطلاعات سفارش نمایش داده شد",
"notif.security.reveal.inapp.body": "اطلاعات سفارش {code} در {time} نمایش داده شد.",
"notif.security.reveal.msg": "اطلاعات سفارش {code} در {time} نمایش داده شد.\nاگر کار شما نبوده، همین حالا به پشتیبانی اطلاع دهید.",

# ── order creation & payment ──
"notif.order.created.inapp.title": "سفارش {code} ثبت شد",
"notif.order.created.inapp.body": "مبلغ {amount} را تا {time} پرداخت کنید.",
"notif.order.created.msg": "سفارش {code} ثبت شد.\nمحصول: {product}\nمبلغ قابل پرداخت: {amount}\nمهلت پرداخت: {time}\nادامه‌ی پرداخت: {url}",
"notif.order.payReminder.inapp.title": "مهلت پرداخت رو به پایان است",
"notif.order.payReminder.inapp.body": "{time} تا پایان مهلت پرداخت سفارش {code} باقی مانده است.",
"notif.order.payReminder.msg": "یادآوری: {time} تا پایان مهلت پرداخت سفارش {code} باقی مانده است.\nادامه‌ی پرداخت: {url}",
"notif.order.expired.inapp.title": "مهلت پرداخت تمام شد",
"notif.order.expired.inapp.body": "سفارش {code} پرداخت نشد و منقضی شد. اگر پرداخت کرده‌اید، رسید را ثبت کنید.",
"notif.order.expired.msg": "مهلت پرداخت سفارش {code} تمام شد.\nاگر مبلغی پرداخت کرده‌اید، رسید را از این پیوند ثبت کنید: {url}",
"notif.payment.receiptReceived.inapp.title": "رسید دریافت شد",
"notif.payment.receiptReceived.inapp.body": "پرداخت سفارش {code} در حال بررسی است.",
"notif.payment.receiptReceived.msg": "رسید سفارش {code} دریافت شد و در حال بررسی است. معمولاً کمتر از {time} طول می‌کشد.",
"notif.payment.confirmed.inapp.title": "پرداخت تأیید شد",
"notif.payment.confirmed.inapp.body": "پرداخت سفارش {code} تأیید شد و سفارش در صف انجام قرار گرفت.",
"notif.payment.confirmed.msg": "پرداخت سفارش {code} تأیید شد.\nتحویل تا حدود {time}.\nپیگیری: {url}",
"notif.payment.confirmed.sms": "{brand}: پرداخت سفارش {code} تأیید شد. پیگیری: {url}",
"notif.payment.rejected.inapp.title": "پرداخت تأیید نشد",
"notif.payment.rejected.inapp.body": "علت: {reason}. می‌توانید اطلاعات را اصلاح و دوباره ثبت کنید.",
"notif.payment.rejected.msg": "پرداخت سفارش {code} تأیید نشد.\nعلت: {reason}\nاصلاح و ثبت دوباره: {url}",
"notif.payment.rejected.sms": "{brand}: پرداخت سفارش {code} تأیید نشد. جزئیات: {url}",
"notif.payment.under.inapp.title": "مبلغ واریزی کمتر بود",
"notif.payment.under.inapp.body": "برای سفارش {code} مبلغ {amount} کم پرداخت شده است.",
"notif.payment.under.msg": "مبلغ واریزی سفارش {code} {amount} کمتر از مبلغ سفارش است.\nتا {time} می‌توانید مابه‌التفاوت را پرداخت کنید: {url}",
"notif.payment.over.inapp.title": "مبلغ اضافی به کیف پول رفت",
"notif.payment.over.inapp.body": "{amount} از پرداخت سفارش {code} به کیف پول شما اضافه شد.",
"notif.payment.over.msg": "مبلغ واریزی سفارش {code} بیش از مبلغ سفارش بود. {amount} به کیف پول شما اضافه شد.",
"notif.payment.late.inapp.title": "پرداخت دیرهنگام دریافت شد",
"notif.payment.late.inapp.body": "پرداخت سفارش {code} پس از مهلت رسید و در حال بررسی است.",
"notif.payment.late.msg": "پرداخت سفارش {code} پس از پایان مهلت رسید. اگر نرخ تغییر نکرده باشد با قیمت قبلی پذیرفته می‌شود، وگرنه گزینه‌های جدید را به شما اعلام می‌کنیم: {url}",
"notif.payment.mismatch.inapp.title": "پرداخت نیازمند بررسی است",
"notif.payment.mismatch.inapp.body": "مبلغ پرداخت‌شده برای سفارش {code} با سفارش یکسان نیست؛ کارشناس بررسی می‌کند.",
"notif.payment.mismatch.msg": "پرداخت سفارش {code} با مبلغ سفارش یکسان نبود و سفارش موقتاً متوقف شد.\nکارشناس موضوع را بررسی می‌کند؛ نیازی به پرداخت دوباره نیست.",
"notif.payment.thirdParty.inapp.title": "پرداخت از حساب دیگر",
"notif.payment.thirdParty.inapp.body": "پرداخت سفارش {code} از حساب شخص دیگری انجام شده و برگشت داده می‌شود.",
"notif.payment.thirdParty.msg": "پرداخت سفارش {code} از کارت یا حساب شخص دیگری انجام شده است. برای امنیت، این مبلغ به صاحب حساب برمی‌گردد. لطفاً از کارت خودتان پرداخت کنید: {url}",

# ── fulfilment ──
"notif.order.riskHold.inapp.title": "سفارش در بررسی امنیتی",
"notif.order.riskHold.inapp.body": "سفارش {code} برای امنیت شما دستی بررسی می‌شود؛ معمولاً کمتر از {time}.",
"notif.order.riskHold.msg": "سفارش {code} برای امنیت شما به‌صورت دستی بررسی می‌شود. معمولاً کمتر از {time} طول می‌کشد و نیازی به اقدام شما نیست.",
"notif.order.started.inapp.title": "کار روی سفارش شروع شد",
"notif.order.started.inapp.body": "سفارش {code} در حال انجام است.",
"notif.order.delayed.inapp.title": "تأخیر در انجام سفارش",
"notif.order.delayed.inapp.body": "سفارش {code} از زمان تعهدشده عقب افتاده است. عذرخواهی می‌کنیم؛ در حال پیگیری هستیم.",
"notif.order.delayed.msg": "سفارش {code} از زمان تعهدشده عقب افتاده است و بابت آن عذرخواهی می‌کنیم. در حال پیگیری هستیم و نتیجه را همین‌جا اطلاع می‌دهیم.\nاگر هزینه‌ی تحویل سریع پرداخت کرده بودید، به‌طور خودکار برگردانده می‌شود.",
"notif.order.delayed.sms": "{brand}: انجام سفارش {code} کمی دیرتر از وعده شد. در حال پیگیری هستیم: {url}",
"notif.order.delivered.inapp.title": "سفارش شما آماده است",
"notif.order.delivered.inapp.body": "اطلاعات سفارش {code} آماده‌ی دریافت است.",
"notif.order.delivered.msg": "سفارش {code} آماده است.\nبرای حفظ امنیت، اطلاعات فقط پس از تأیید کد پیامکی در سایت نمایش داده می‌شود: {url}",
"notif.order.delivered.sms": "{brand}: سفارش {code} آماده است. دریافت: {url}",
"notif.order.delivered.email.subject": "سفارش {code} آماده است",
"notif.order.delivered.email.body": "سفارش {code} در {brand} آماده‌ی دریافت است. برای حفظ امنیت، اطلاعات کارت یا کد در ایمیل ارسال نمی‌شود. از این پیوند وارد شوید و پس از تأیید هویت آن را ببینید: {url}",
"notif.order.completed.inapp.title": "سفارش تکمیل شد",
"notif.order.completed.inapp.body": "سفارش {code} تکمیل شد. از اعتماد شما سپاسگزاریم.",
"notif.order.completed.msg": "سفارش {code} تکمیل شد. از اعتماد شما سپاسگزاریم. اگر مشکلی هست از همین‌جا گزارش دهید: {url}",
"notif.order.failed.inapp.title": "انجام سفارش ممکن نشد",
"notif.order.failed.inapp.body": "سفارش {code} انجام نشد. بازگشت وجه یا تلاش از مسیر دیگر را انتخاب کنید.",
"notif.order.failed.msg": "انجام سفارش {code} ممکن نشد.\nمی‌توانید بازگشت وجه بگیرید یا با موافقت شما از مسیر دیگری تلاش کنیم: {url}",
"notif.order.failed.sms": "{brand}: انجام سفارش {code} ممکن نشد. گزینه‌های شما: {url}",
"notif.order.refundPending.inapp.title": "بازگشت وجه ثبت شد",
"notif.order.refundPending.inapp.body": "مبلغ {amount} تا {time} به {target} واریز می‌شود.",
"notif.order.refundPending.msg": "بازگشت وجه سفارش {code} ثبت شد.\nمبلغ: {amount}\nواریز تا: {time}\nمقصد: {target}",
"notif.order.refunded.inapp.title": "مبلغ بازگردانده شد",
"notif.order.refunded.inapp.body": "{amount} از سفارش {code} بازگردانده شد.",
"notif.order.refunded.msg": "{amount} از سفارش {code} به {target} بازگردانده شد.",
"notif.order.refunded.sms": "{brand}: مبلغ {amount} از سفارش {code} بازگردانده شد.",
"notif.rush.refunded.inapp.title": "هزینه‌ی تحویل سریع برگشت",
"notif.rush.refunded.inapp.body": "به دلیل تأخیر در سفارش {code}، {amount} هزینه‌ی تحویل سریع برگردانده شد.",
"notif.rush.refunded.msg": "به دلیل تأخیر در سفارش {code}، هزینه‌ی تحویل سریع ({amount}) به {target} برگردانده شد.",
"notif.dispute.opened.inapp.title": "گزارش شما ثبت شد",
"notif.dispute.opened.inapp.body": "گزارش مشکل سفارش {code} ثبت شد و بررسی می‌شود.",
"notif.dispute.opened.msg": "گزارش مشکل سفارش {code} ثبت شد. نتیجه را ظرف {time} اعلام می‌کنیم.",
"notif.dispute.resolved.inapp.title": "نتیجه‌ی گزارش شما",
"notif.dispute.resolved.inapp.body": "گزارش سفارش {code} بررسی شد: {outcome}.",
"notif.dispute.resolved.msg": "گزارش سفارش {code} بررسی شد.\nنتیجه: {outcome}\nجزئیات: {url}",

# ── wallet / referral / kyc / support / system ──
"notif.wallet.topup.inapp.title": "کیف پول شارژ شد",
"notif.wallet.topup.inapp.body": "{amount} به کیف پول شما اضافه شد.",
"notif.wallet.topup.msg": "{amount} به کیف پول شما اضافه شد. موجودی فعلی: {balance}.",
"notif.referral.reward.inapp.title": "پاداش دعوت دریافت شد",
"notif.referral.reward.inapp.body": "{amount} پاداش دعوت به کیف پول شما اضافه شد.",
"notif.referral.reward.msg": "یکی از دعوت‌شدگان شما اولین سفارش خود را تکمیل کرد. {amount} پاداش به کیف پول شما اضافه شد.",
"notif.kyc.verified.inapp.title": "هویت شما تأیید شد",
"notif.kyc.verified.inapp.body": "سقف جدید حساب شما فعال شد.",
"notif.kyc.verified.msg": "هویت شما تأیید شد و سقف جدید حساب شما فعال است.",
"notif.kyc.verified.sms": "{brand}: هویت شما تأیید شد و سقف جدید فعال است.",
"notif.kyc.rejected.inapp.title": "تأیید هویت انجام نشد",
"notif.kyc.rejected.inapp.body": "علت: {reason}. اطلاعات را اصلاح و دوباره ثبت کنید.",
"notif.kyc.rejected.msg": "تأیید هویت انجام نشد.\nعلت: {reason}\nاصلاح و ثبت دوباره: {url}",
"notif.ticket.reply.inapp.title": "پاسخ پشتیبانی",
"notif.ticket.reply.inapp.body": "پشتیبانی به درخواست {id} پاسخ داد.",
"notif.ticket.reply.msg": "پشتیبانی به درخواست {id} شما پاسخ داد: {url}",
"notif.ticket.reply.email.subject": "پاسخ به درخواست {id}",
"notif.ticket.reply.email.body": "پشتیبانی {brand} به درخواست {id} شما پاسخ داد. برای دیدن پاسخ وارد حساب خود شوید: {url}",
"notif.product.backInStock.inapp.title": "محصول دوباره فعال شد",
"notif.product.backInStock.inapp.body": "{product} دوباره در دسترس است.",
"notif.product.backInStock.msg": "{product} که خواسته بودید خبر بدهیم، دوباره در دسترس است: {url}",
"notif.system.salesPaused.inapp.title": "فروش موقتاً متوقف است",
"notif.system.salesPaused.inapp.body": "ثبت سفارش جدید موقتاً غیرفعال است؛ سفارش‌های قبلی ادامه می‌یابد.",
"notif.system.salesResumed.inapp.title": "فروش دوباره فعال شد",
"notif.system.salesResumed.inapp.body": "ثبت سفارش جدید دوباره ممکن است.",
"notif.legal.termsUpdated.inapp.title": "شرایط استفاده به‌روز شد",
"notif.legal.termsUpdated.inapp.body": "نسخه‌ی {version} منتشر شد. لطفاً آن را بخوانید.",
"notif.legal.termsUpdated.email.subject": "به‌روزرسانی شرایط استفاده {brand}",
"notif.legal.termsUpdated.email.body": "نسخه‌ی {version} از شرایط استفاده {brand} منتشر شد. متن کامل: {url}",

# ── messenger buttons ──
"notif.btn.pay": "ادامه‌ی پرداخت",
"notif.btn.track": "پیگیری سفارش",
"notif.btn.receive": "دریافت اطلاعات",
"notif.btn.support": "پشتیبانی",
"notif.btn.openApp": "باز کردن {brand}",
"notif.btn.receipt": "ثبت رسید",

# ── staff / admin notifications (in-app + staff Telegram/Bale group) ──
"notif.admin.paymentReview.inapp.title": "پرداخت در انتظار بررسی",
"notif.admin.paymentReview.inapp.body": "سفارش {code} — {amount} — روش: {method}",
"notif.admin.paymentReview.msg": "پرداخت در انتظار بررسی\nسفارش: {code}\nمبلغ: {amount}\nروش: {method}\nباز کردن: {url}",
"notif.admin.slaWarn.inapp.title": "نزدیک به نقض زمان تعهدشده",
"notif.admin.slaWarn.inapp.body": "سفارش {code} ({tier}) تا {time} دیگر مهلت دارد.",
"notif.admin.slaWarn.msg": "هشدار زمان: سفارش {code} ({tier}) تا {time} دیگر مهلت دارد.\n{url}",
"notif.admin.slaBreach.inapp.title": "نقض زمان تعهدشده",
"notif.admin.slaBreach.inapp.body": "سفارش {code} از زمان تعهدشده گذشته؛ هزینه‌ی سرعت برگردانده می‌شود.",
"notif.admin.killSwitch.inapp.title": "کلید توقف فروش فعال شد",
"notif.admin.killSwitch.inapp.body": "علت: {reason}. دامنه: {scope}.",
"notif.admin.killSwitch.msg": "کلید توقف فعال شد\nعلت: {reason}\nدامنه: {scope}\n{url}",
"notif.admin.providerFail.inapp.title": "خطای مکرر ارائه‌دهنده",
"notif.admin.providerFail.inapp.body": "نرخ خطای {provider}: {pct}",
"notif.admin.providerFail.msg": "خطای مکرر ارائه‌دهنده {provider}: نرخ خطا {pct}\n{url}",
"notif.admin.lowFloat.inapp.title": "موجودی ارائه‌دهنده کم است",
"notif.admin.lowFloat.inapp.body": "{provider}: پوشش {days} روز (حداقل هدف: {min} روز).",
"notif.admin.lowFloat.msg": "موجودی کم: {provider}\nپوشش فعلی: {days} روز\nحداقل هدف: {min} روز\n{url}",
"notif.admin.rateAnomaly.inapp.title": "ناهمگونی نرخ صرافی‌ها",
"notif.admin.rateAnomaly.inapp.body": "پراکندگی نرخ‌ها {pct} است و از آستانه گذشته.",
"notif.admin.riskFlag.inapp.title": "پرچم ریسک تازه",
"notif.admin.riskFlag.inapp.body": "مشتری {customer} — {flag} — امتیاز {score}",
"notif.admin.largeOrder.inapp.title": "سفارش بزرگ",
"notif.admin.largeOrder.inapp.body": "سفارش {code} به مبلغ {amount} نیازمند تأیید است.",
"notif.admin.unmatchedPayment.inapp.title": "واریز نامشخص",
"notif.admin.unmatchedPayment.inapp.body": "{amount} در {time} به هیچ سفارشی منطبق نشد.",
}

# Lint/compliance fixes for strings that live in the web snapshot (apps/web/src/copy/fa.ts); web owner should adopt these.
OVERRIDE = {
"quote.lockHint": "این قیمت تا پایان تایمر برای شما قفل است.",
"quote.savingsNote": "مقایسه با نرخ مرجع بازار در همین لحظه انجام شده و پیش‌بینی قیمت آینده نیست.",
"system.ratesHaltedBody": "بازار ارز محدود یا بسته است؛ قیمت‌ها با احتیاط بیشتری محاسبه می‌شوند.",
}
COPY["notif.auth.otp.sms"] = "کد تأیید {brand}: {code}\nبه کسی ندهید.\n@{domain} #{code}"
