# -*- coding: utf-8 -*-
"""Copy part 1: brand, home, catalogue, product, live calculator, quote lock, rush/express."""
COPY = {
# ── brand / seo ──
"brand.tagline": "پرداخت خارجی، ساده و شفاف",
"brand.footerAbout": "{brand} واسطه‌ی خرید کارت مجازی بین‌المللی و خدمات دیجیتال است. قیمت نهایی، کارمزدها و محدودیت‌های هر محصول را پیش از پرداخت می‌بینید.",
"seo.home.title": "{brand} | کارت مجازی و خدمات دیجیتال با قیمت شفاف",
"seo.home.description": "کارت مجازی بین‌المللی، شارژ کارت و خدمات دیجیتال با پرداخت به تومان. قیمت نهایی پیش از پرداخت، پیگیری مرحله‌به‌مرحله‌ی سفارش و پشتیبانی فارسی.",
"seo.catalog.title": "محصولات | {brand}",
"seo.product.title": "{product} | {brand}",
"seo.legal.title": "{page} | {brand}",

# ── home ──
"home.hero.title": "کارت مجازی و خدمات دیجیتال، با قیمت نهایی روشن",
"home.hero.subtitle": "مبلغ را وارد کنید، قیمت کامل را با تمام کارمزدها ببینید و به تومان پرداخت کنید. سفارش شما مرحله‌به‌مرحله قابل پیگیری است.",
"home.hero.cta": "محاسبه‌ی قیمت",
"home.hero.ctaSecondary": "دیدن محصولات",
"home.board.title": "قیمت امروز خدمات",
"home.board.updated": "به‌روزرسانی: {time}",
"home.board.fromPrice": "از {amount}",
"home.board.baseRate": "نرخ پایه‌ی محاسبه‌ی هر ۱ دلار اعتبار",
"home.board.baseRateNote": "کارمزدها جداگانه در قیمت نهایی هر سفارش نمایش داده می‌شود.",
"home.board.stale": "نرخ در حال به‌روزرسانی است؛ قیمت نهایی در لحظه‌ی سفارش محاسبه می‌شود.",
"home.board.empty": "قیمت‌ها هنوز بارگذاری نشده‌اند.",
"home.board.cta": "محاسبه‌ی قیمت دقیق",
"home.trust.title": "چرا می‌توانید به ما اطمینان کنید",
"home.trust.price": "قیمت نهایی، شامل کارمزد و مالیات، پیش از پرداخت نمایش داده می‌شود.",
"home.trust.tracking": "هر سفارش خط زمانی دارد؛ از پرداخت تا تحویل را می‌بینید.",
"home.trust.support": "پشتیبانی فارسی {hours}.",
"home.trust.refund": "قواعد بازگشت وجه روشن و مرحله‌به‌مرحله است.",
"home.trust.risk": "ریسک و محدودیت هر محصول را پیش از خرید می‌خوانید.",
"home.trust.enamad": "نماد اعتماد الکترونیکی",
"home.trust.legalName": "{legalName} — شماره‌ی ثبت {regNo}",
"home.how.title": "چطور کار می‌کند",
"home.how.step1.title": "محصول و مبلغ",
"home.how.step1.body": "محصول را انتخاب و مبلغ را وارد کنید؛ قیمت نهایی همان لحظه محاسبه می‌شود.",
"home.how.step2.title": "پرداخت به تومان",
"home.how.step2.body": "با درگاه بانکی، کارت‌به‌کارت یا روش‌های دیگر پرداخت کنید.",
"home.how.step3.title": "تحویل و پیگیری",
"home.how.step3.body": "وضعیت سفارش را زنده می‌بینید و اطلاعات را با یک تأیید امنیتی دریافت می‌کنید.",
"home.popular.title": "محصولات پرطرفدار",
"home.faq.title": "سؤالات متداول",
"home.faq.seeAll": "همه‌ی پرسش‌ها",
"home.recent.title": "ادامه‌ی سفارش‌های اخیر",
"home.recent.reorder": "سفارش دوباره",
"home.banner.rushOpen": "ظرفیت سفارش سریع امروز باز است.",
"home.footer.disclaimer": "خدمات خارجی توسط ارائه‌دهندگان شخص ثالث ارائه می‌شود و ممکن است برای کاربران ایران محدودیت داشته باشد. پیش از خرید «افشای ریسک» را بخوانید.",

# ── catalogue ──
"catalog.title": "محصولات",
"catalog.subtitle": "قیمت‌ها بر اساس نرخ و هزینه‌ی همین لحظه محاسبه می‌شوند.",
"catalog.search": "جستجوی محصول",
"catalog.filter.all": "همه",
"catalog.filter.cards": "کارت مجازی",
"catalog.filter.topup": "شارژ کارت",
"catalog.filter.vouchers": "گیفت‌کارت",
"catalog.filter.subscriptions": "اشتراک‌ها",
"catalog.filter.services": "پرداخت خدمات",
"catalog.filter.riskLabel": "سطح ریسک",
"catalog.sort.label": "مرتب‌سازی",
"catalog.sort.popular": "پرطرفدار",
"catalog.sort.priceAsc": "ارزان‌ترین",
"catalog.sort.fastest": "سریع‌ترین",
"catalog.card.from": "از {amount}",
"catalog.card.sla": "تحویل تا {time}",
"catalog.card.auto": "تحویل خودکار",
"catalog.card.operator": "با بررسی کارشناس",
"catalog.card.unavailable": "فعلاً موجود نیست",
"catalog.card.unavailableReason": "این محصول موقتاً متوقف شده است.",
"catalog.empty.title": "محصولی پیدا نشد",
"catalog.empty.body": "عبارت جستجو یا فیلترها را تغییر دهید.",
"catalog.empty.reset": "پاک کردن فیلترها",
"catalog.error.title": "بارگذاری محصولات ممکن نشد",
"catalog.loading": "در حال بارگذاری محصولات…",
"catalog.count": "{n} محصول",

# ── product detail ──
"product.back": "بازگشت به محصولات",
"product.amount.label": "مبلغ (دلار)",
"product.amount.options": "یکی از مبلغ‌ها را انتخاب کنید",
"product.amount.custom": "مبلغ دلخواه",
"product.amount.range": "از {min} تا {max}",
"product.amount.help": "مبلغ، اعتبار نهایی سرویس است؛ کارمزدها جداگانه نمایش داده می‌شود.",
"product.inputs.title": "اطلاعات موردنیاز",
"product.includes.title": "این سفارش شامل",
"product.includes.cardIssue": "صدور کارت مجازی جدید",
"product.includes.topup": "شارژ اعتبار کارت",
"product.sla.title": "زمان تحویل",
"product.sla.normal": "حدود {time}",
"product.sla.businessHours": "خارج از ساعت کاری، زمان از شروع ساعت کاری ({hours}) حساب می‌شود.",
"product.risk.title": "ریسک و محدودیت این محصول",
"product.risk.readFull": "مطالعه‌ی کامل افشای ریسک",
"product.restriction.generic": "ارائه‌دهنده‌ی این سرویس ممکن است برای کاربران ایران محدودیت داشته باشد.",
"product.howToUse.title": "نحوه‌ی استفاده",
"product.faq.title": "پرسش‌های این محصول",
"product.unavailable.title": "این محصول فعلاً در دسترس نیست",
"product.unavailable.body": "فروش آن موقتاً متوقف شده است. می‌توانید خبرم کن را بزنید تا هنگام فعال‌شدن اطلاع بدهیم.",
"product.notify": "خبرم کن",
"product.notifyDone": "هنگام فعال‌شدن اطلاع می‌دهیم.",
"product.loading": "در حال بارگذاری محصول…",
"product.notFound": "این محصول پیدا نشد.",

# ── live calculator / price breakdown ──
"calc.title": "قیمت نهایی شما",
"calc.subtitle": "قیمت با نرخ و هزینه‌ی همین لحظه محاسبه شده است.",
"calc.line.service_value": "ارزش سرویس",
"calc.line.provider_fees": "کارمزد صدور و شارژ کارت",
"calc.line.exchange_cost": "هزینه‌ی تأمین و تبدیل",
"calc.line.volatility_buffer": "هزینه‌ی تثبیت قیمت",
"calc.line.conversion_and_lock": "هزینه‌ی تأمین و تثبیت قیمت",
"calc.line.risk_buffer": "پوشش ریسک عملیات",
"calc.line.service_fee": "کارمزد خدمات {brand}",
"calc.line.payment_fee": "کارمزد روش پرداخت",
"calc.line.margin": "کارمزد خدمات {brand}",
"calc.line.rush": "هزینه‌ی تحویل {tier}",
"calc.line.vat": "مالیات بر ارزش افزوده",
"calc.line.rounding": "گردکردن",
"calc.line.discount": "تخفیف",
"calc.line.total": "مبلغ قابل پرداخت",
"calc.tip.provider_fees": "هزینه‌هایی که ارائه‌دهنده‌ی کارت برای صدور و شارژ دریافت می‌کند و بدون افزودن سود منتقل می‌شود.",
"calc.tip.conversion_and_lock": "هزینه‌ی تبدیل تومان به اعتبار ارزی و پوشش نوسان نرخ در مدت قفل قیمت. این بخش برگشت‌داده نمی‌شود.",
"calc.tip.service_fee": "کارمزد {brand} برای خدمت‌رسانی، پشتیبانی و ریسک عملیات.",
"calc.tip.payment_fee": "کارمزد روش پرداختی که انتخاب می‌کنید؛ در کارت‌به‌کارت صفر است.",
"calc.tip.rush": "هزینه‌ی اختیاری برای تحویل سریع‌تر. در صورت رعایت‌نشدن زمان تعهدشده برگردانده می‌شود.",
"calc.tip.vat": "طبق قوانین مالیاتی، در صورت شمول به قیمت اضافه می‌شود.",
"calc.effectiveRate": "نرخ مؤثر: هر ۱ دلار اعتبار = {rate}",
"calc.effectiveRateNote": "این نرخ شامل همه‌ی هزینه‌های بالا (به جز هزینه‌ی تحویل سریع و کارمزد پرداخت) است.",
"calc.finalPriceNote": "قیمت نهایی شامل همه‌ی کارمزدها و مالیات است؛ هزینه‌ی دیگری اضافه نمی‌شود.",
"calc.byMethod": "قیمت بر حسب روش پرداخت",
"calc.method.gateway": "درگاه بانکی",
"calc.method.card_to_card": "کارت‌به‌کارت",
"calc.method.bank_transfer": "انتقال بانکی",
"calc.method.usdt": "تتر (USDT)",
"calc.method.wallet": "کیف پول",
"calc.method.unavailable": "در حال حاضر در دسترس نیست",
"calc.cheapest": "کم‌هزینه‌ترین روش",
"calc.market.title": "مقایسه با بازار",
"calc.market.cheaper": "حدود {pct} کمتر از میانگین قیمت‌های بررسی‌شده",
"calc.market.similar": "نزدیک به میانگین قیمت‌های بررسی‌شده",
"calc.market.source": "بر اساس {n} فروشنده؛ بررسی شده در {time}.",
"calc.market.hidden": "مقایسه‌ی بازار در دسترس نیست.",
"calc.compute.loading": "در حال محاسبه‌ی قیمت…",
"calc.compute.error": "محاسبه‌ی قیمت انجام نشد. دوباره تلاش کنید.",
"calc.amount.tooLow": "حداقل مبلغ این محصول {min} است.",
"calc.amount.tooHigh": "حداکثر مبلغ این محصول {max} است.",
"calc.amount.overLimit": "این مبلغ از سقف سطح حساب شما ({limit}) بیشتر است.",
"calc.amount.overLimitCta": "افزایش سقف با تأیید هویت",
"calc.warning.uncompetitive": "قیمت این محصول اکنون بالاتر از میانگین بازار است؛ ممکن است ارزان‌تر شود.",
"calc.warning.haltPremium": "بازار موقتاً محدود است و قیمت با احتیاط بیشتری محاسبه شده است.",
"calc.warning.staleRate": "نرخ تازه نیست؛ قیمت نهایی هنگام ثبت سفارش تأیید می‌شود.",
"calc.continue": "ادامه و انتخاب روش پرداخت",
"calc.blocked.title": "ثبت سفارش موقتاً ممکن نیست",

# ── quote lock / price changed ──
"quote.lock.label": "قیمت تا {time} ثابت است",
"quote.lock.countdown": "{time} تا پایان قفل قیمت",
"quote.lock.explain": "قیمت شما برای مدتی ثابت می‌ماند؛ حتی اگر نرخ تغییر کند، همین مبلغ را پرداخت می‌کنید.",
"quote.lock.expiringSoon": "کمتر از {time} به پایان قفل قیمت مانده است.",
"quote.lock.expired.title": "قفل قیمت تمام شد",
"quote.lock.expired.body": "برای ادامه، قیمت را با نرخ تازه محاسبه می‌کنیم. اگر پیش‌تر پرداخت کرده‌اید، نگران نباشید؛ پرداخت شما بررسی می‌شود.",
"quote.lock.refresh": "قیمت تازه",
"quote.changed.title": "قیمت تغییر کرد",
"quote.changed.body": "قیمت قبلی {old} بود و اکنون {new} است ({diff}).",
"quote.changed.up": "افزایش {diff}",
"quote.changed.down": "کاهش {diff}",
"quote.changed.accept": "پذیرش قیمت جدید",
"quote.changed.cancel": "انصراف",
"quote.changed.why": "نرخ‌های بازار تغییر کرده‌اند. ما قیمت را فقط با تغییر واقعی هزینه به‌روز می‌کنیم.",
"quote.id": "شناسه‌ی قیمت: {id}",

# ── rush / express ──
"rush.title": "سرعت تحویل",
"rush.subtitle": "اختیاری است؛ می‌توانید روی حالت عادی بمانید.",
"rush.tier.normal": "عادی",
"rush.tier.fast": "سریع",
"rush.tier.express": "فوری",
"rush.tier.normal.hint": "ترتیب معمول صف",
"rush.tier.fast.hint": "اولویت در صف",
"rush.tier.express.hint": "بالاترین اولویت",
"rush.eta": "تحویل تا {time}",
"rush.extra": "+{amount}",
"rush.free": "بدون هزینه‌ی اضافه",
"rush.capacity.available": "ظرفیت این ساعت: {left} از {total}",
"rush.capacity.low": "فقط {left} جای باقی‌مانده در این ساعت",
"rush.capacity.full": "ظرفیت این ساعت پر است؛ نزدیک‌ترین زمان: {time}",
"rush.capacity.note": "ظرفیت واقعی تیم عملیات است و برای ترغیب تغییر نمی‌کند.",
"rush.afterHours": "خارج از ساعت کاری ({hours}) زمان تحویل از شروع ساعت کاری حساب می‌شود.",
"rush.unavailable": "این سرعت فعلاً در دسترس نیست.",
"rush.guarantee": "اگر زمان تعهدشده رعایت نشود، هزینه‌ی تحویل سریع به‌طور خودکار برگردانده می‌شود.",
"rush.guarantee.refundedNote": "هزینه‌ی تحویل سریع این سفارش به دلیل تأخیر برگردانده شد.",
"rush.upgrade.cta": "سریع‌ترش کن",
"rush.upgrade.title": "افزایش سرعت این سفارش",
"rush.upgrade.body": "تا زمانی که کارشناس کار را شروع نکرده، می‌توانید سرعت را افزایش دهید. فقط مابه‌التفاوت پرداخت می‌شود.",
"rush.upgrade.diff": "مابه‌التفاوت: {amount}",
"rush.upgrade.tooLate": "کار این سفارش شروع شده و افزایش سرعت ممکن نیست.",
"rush.upgrade.confirm": "پرداخت مابه‌التفاوت",
"rush.noDefault": "حالت عادی از پیش انتخاب شده است.",
}
