# -*- coding: utf-8 -*-
"""Copy part 5: admin / operator panel (/admin) and the demo simulation panel."""
COPY = {
# ── shell / nav ──
"admin.title": "پنل مدیریت",
"admin.login.title": "ورود کارکنان",
"admin.login.username": "نام کاربری",
"admin.login.password": "گذرواژه",
"admin.login.totp": "کد برنامه‌ی تأیید دومرحله‌ای",
"admin.login.submit": "ورود",
"admin.login.failed": "نام کاربری یا گذرواژه درست نیست.",
"admin.login.locked": "حساب به‌دلیل تلاش‌های ناموفق موقتاً قفل شد.",
"admin.nav.dashboard": "داشبورد",
"admin.nav.queue": "صف سفارش‌ها",
"admin.nav.orders": "سفارش‌ها",
"admin.nav.payments": "تطبیق پرداخت‌ها",
"admin.nav.tasks": "کنسول انجام",
"admin.nav.treasury": "خزانه‌داری",
"admin.nav.pricing": "قیمت‌گذاری",
"admin.nav.rates": "نرخ‌ها و کلید توقف",
"admin.nav.catalog": "کاتالوگ",
"admin.nav.customers": "مشتریان",
"admin.nav.risk": "پرچم‌های ریسک",
"admin.nav.tickets": "تیکت‌ها",
"admin.nav.reports": "گزارش‌ها",
"admin.nav.audit": "سابقه‌ی تغییرات",
"admin.nav.users": "کاربران و دسترسی‌ها",
"admin.nav.settings": "تنظیمات",
"admin.nav.sim": "شبیه‌ساز",
"admin.role.owner": "مالک",
"admin.role.admin": "مدیر",
"admin.role.operator": "اپراتور",
"admin.role.support": "پشتیبان",
"admin.role.accountant": "حسابدار",
"admin.role.viewer": "ناظر",
"admin.forbidden.title": "دسترسی ندارید",
"admin.forbidden.body": "نقش «{role}» اجازه‌ی این عملیات را ندارد.",
"admin.session.expiring": "نشست شما تا {time} دیگر پایان می‌یابد.",
"admin.stepUp.title": "تأیید مجدد برای عملیات حساس",
"admin.stepUp.body": "برای این عملیات گذرواژه یا کد دومرحله‌ای را دوباره وارد کنید.",
"admin.twoPerson.title": "نیازمند تأیید نفر دوم",
"admin.twoPerson.body": "این عملیات باید توسط یک کاربر دیگر با نقش مالک یا مدیر تأیید شود.",

# ── dashboard ──
"admin.dash.title": "نمای کلی امروز",
"admin.dash.ordersToday": "سفارش‌های امروز",
"admin.dash.revenueToday": "فروش امروز",
"admin.dash.marginToday": "حاشیه‌ی سود امروز",
"admin.dash.openQueue": "در صف انجام",
"admin.dash.slaAtRisk": "در خطر نقض زمان",
"admin.dash.paymentsToReview": "پرداخت در انتظار بررسی",
"admin.dash.floatCoverage": "پوشش موجودی",
"admin.dash.floatCoverageDays": "{days} روز",
"admin.dash.alerts": "هشدارهای فعال",
"admin.dash.noAlerts": "هشدار فعالی وجود ندارد.",
"admin.dash.rateStatus": "وضعیت نرخ",
"admin.dash.killSwitch": "کلید توقف",
"admin.dash.updated": "آخرین به‌روزرسانی: {time}",
"admin.dash.loading": "در حال بارگذاری داشبورد…",
"admin.dash.error": "بارگذاری داشبورد ممکن نشد.",

# ── order queue / detail ──
"admin.queue.title": "صف سفارش‌ها",
"admin.queue.tab.payments": "پرداخت‌ها",
"admin.queue.tab.risk": "بررسی ریسک",
"admin.queue.tab.fulfil": "انجام",
"admin.queue.tab.disputes": "اعتراض‌ها",
"admin.queue.col.code": "کد",
"admin.queue.col.customer": "مشتری",
"admin.queue.col.product": "محصول",
"admin.queue.col.amount": "مبلغ",
"admin.queue.col.tier": "سرعت",
"admin.queue.col.sla": "مهلت",
"admin.queue.col.status": "وضعیت",
"admin.queue.col.owner": "مسئول",
"admin.queue.empty": "صف خالی است؛ کار تازه‌ای نیست.",
"admin.queue.filter.mine": "فقط مال من",
"admin.queue.filter.unassigned": "بدون مسئول",
"admin.queue.filter.rush": "فقط سریع و فوری",
"admin.queue.sort.sla": "نزدیک‌ترین مهلت",
"admin.queue.claim": "برداشتن",
"admin.queue.claimed": "به شما اختصاص یافت.",
"admin.queue.claimedByOther": "این مورد را {name} برداشته است.",
"admin.queue.slaOk": "در زمان",
"admin.queue.slaWarn": "نزدیک مهلت",
"admin.queue.slaBreached": "از مهلت گذشته",
"admin.queue.autoRefresh": "به‌روزرسانی زنده فعال است.",
"admin.queue.disconnected": "ارتباط زنده قطع شد؛ در حال اتصال دوباره…",
"admin.order.title": "سفارش {code}",
"admin.order.section.customer": "مشتری",
"admin.order.section.payment": "پرداخت",
"admin.order.section.fulfilment": "انجام",
"admin.order.section.pricing": "قیمت و حاشیه‌ی سود",
"admin.order.section.timeline": "سابقه‌ی سفارش",
"admin.order.section.notes": "یادداشت‌های داخلی",
"admin.order.cost": "هزینه‌ی تأمین",
"admin.order.margin": "حاشیه‌ی سود",
"admin.order.marginPct": "درصد حاشیه",
"admin.order.rateAtQuote": "نرخ زمان قیمت‌گذاری",
"admin.order.rateNow": "نرخ فعلی",
"admin.order.policyVersion": "نسخه‌ی سیاست قیمت",
"admin.order.riskScore": "امتیاز ریسک",
"admin.order.action.approvePayment": "تأیید پرداخت",
"admin.order.action.rejectPayment": "رد پرداخت",
"admin.order.action.hold": "نگه‌داشتن برای بررسی",
"admin.order.action.release": "آزادسازی",
"admin.order.action.cancel": "لغو سفارش",
"admin.order.action.refund": "بازگشت وجه",
"admin.order.action.retry": "تلاش دوباره",
"admin.order.action.addNote": "افزودن یادداشت",
"admin.order.confirm.approve": "پرداخت سفارش {code} به مبلغ {amount} تأیید شود؟",
"admin.order.confirm.refund": "مبلغ {amount} به {target} برگردانده شود؟ این عملیات برگشت‌پذیر نیست.",
"admin.order.reasonRequired": "ثبت علت الزامی است.",
"admin.order.reason.label": "علت",
"admin.order.reason.placeholder": "علت را کوتاه بنویسید؛ در سابقه ثبت می‌شود.",
"admin.order.versionConflict": "این سفارش هم‌زمان تغییر کرده است؛ صفحه را تازه کنید.",
"admin.order.done": "انجام شد.",

# ── payment matching ──
"admin.pay.title": "تطبیق پرداخت‌ها",
"admin.pay.tab.review": "در انتظار بررسی",
"admin.pay.tab.unmatched": "واریزهای نامشخص",
"admin.pay.tab.history": "سابقه",
"admin.pay.expected": "مبلغ مورد انتظار",
"admin.pay.received": "مبلغ دریافتی",
"admin.pay.diff": "اختلاف",
"admin.pay.receipt": "رسید مشتری",
"admin.pay.trackingNo": "شماره‌ی پیگیری",
"admin.pay.payerLast4": "چهار رقم آخر کارت پرداخت‌کننده",
"admin.pay.statementCredit": "واریز در صورت‌حساب بانک",
"admin.pay.suggested": "پیشنهاد سامانه",
"admin.pay.matchScore": "اطمینان تطبیق: {pct}",
"admin.pay.match": "تطبیق با این سفارش",
"admin.pay.noMatch": "سفارشی برای تطبیق پیدا نشد.",
"admin.pay.duplicateRef": "این شماره‌ی پیگیری قبلاً استفاده شده است.",
"admin.pay.nameMismatch": "نام پرداخت‌کننده با مشتری یکسان نیست.",
"admin.pay.thirdParty": "پرداخت‌کننده با مشتری یکسان نیست؛ طبق سیاست باید برگردانده شود.",
"admin.pay.underpaid": "کم‌پرداخت",
"admin.pay.overpaid": "بیش‌پرداخت",
"admin.pay.late": "دیرهنگام",
"admin.pay.matched": "تطبیق انجام شد.",
"admin.pay.imageViewer": "تصویر رسید",
"admin.pay.statementUpload": "بارگذاری صورت‌حساب بانکی",
"admin.pay.statementEmpty": "هنوز صورت‌حسابی بارگذاری نشده است.",
"admin.pay.gatewayMismatch": "ناهمخوانی درگاه: هرگز بدون بررسی انجام نشود.",

# ── fulfilment console ──
"admin.task.title": "کنسول انجام",
"admin.task.kind.issue_card": "صدور کارت",
"admin.task.kind.topup_card": "شارژ کارت",
"admin.task.kind.deliver_voucher": "تحویل کد",
"admin.task.kind.pay_service": "پرداخت خدمت",
"admin.task.kind.custom": "سفارشی",
"admin.task.status.queued": "در صف",
"admin.task.status.claimed": "برداشته‌شده",
"admin.task.status.in_progress": "در حال انجام",
"admin.task.status.done": "انجام‌شده",
"admin.task.status.failed": "ناموفق",
"admin.task.status.cancelled": "لغوشده",
"admin.task.steps": "مراحل انجام",
"admin.task.checklist.fundsReady": "اعتبار ارائه‌دهنده کافی است",
"admin.task.checklist.inputsChecked": "اطلاعات مشتری بررسی شد",
"admin.task.checklist.done": "عملیات در پنل ارائه‌دهنده انجام شد",
"admin.task.checklist.verified": "نتیجه بررسی شد",
"admin.task.deliveryPayload": "اطلاعات تحویل",
"admin.task.deliveryHint": "اطلاعات حساس رمزگذاری و ذخیره می‌شود و در سابقه نمایش داده نمی‌شود.",
"admin.task.complete": "ثبت تحویل",
"admin.task.fail": "ثبت شکست",
"admin.task.failReason": "علت شکست",
"admin.task.release": "رها کردن",
"admin.task.claim": "برداشتن",
"admin.task.noFunds": "اعتبار ارائه‌دهنده کافی نیست؛ سفارش در انتظار تأمین می‌ماند.",
"admin.task.elapsed": "زمان سپری‌شده: {time}",
"admin.task.sla.left": "{time} تا مهلت",
"admin.task.sla.over": "{time} از مهلت گذشته",
"admin.task.attempts": "تلاش {n} از {max}",
"admin.task.altProvider": "ارائه‌دهنده‌ی جایگزین",
"admin.task.neverAsk": "هرگز از مشتری رمز، CVV2 یا کد پیامکی نخواهید.",
"admin.task.productivity": "عملکرد شما امروز: {n} سفارش، میانگین {time}",

# ── treasury ──
"admin.treasury.title": "خزانه‌داری",
"admin.treasury.balances": "موجودی‌ها",
"admin.treasury.bank": "حساب بانکی",
"admin.treasury.exchange": "صرافی {name}",
"admin.treasury.wallet": "کیف پول زنجیره‌ای",
"admin.treasury.provider": "ارائه‌دهنده {name}",
"admin.treasury.inTransit": "در راه",
"admin.treasury.locked": "قفل‌شده (محدودیت برداشت)",
"admin.treasury.unlocked": "آزاد",
"admin.treasury.unlockAt": "آزادسازی: {time}",
"admin.treasury.coverage": "پوشش تقاضا",
"admin.treasury.coverageDays": "{days} روز",
"admin.treasury.target": "هدف: {days} روز",
"admin.treasury.coverage.low": "کمتر از حداقل هدف",
"admin.treasury.coverage.ok": "در محدوده‌ی هدف",
"admin.treasury.coverage.high": "بیش از حد (ریسک نوسان نرخ)",
"admin.treasury.forecast": "پیش‌بینی تقاضا",
"admin.treasury.plan": "برنامه‌ی تأمین پیشنهادی",
"admin.treasury.plan.empty": "فعلاً اقدامی لازم نیست.",
"admin.treasury.plan.execute": "اجرای برنامه",
"admin.treasury.plan.step.deposit": "واریز تومان به صرافی",
"admin.treasury.plan.step.buy": "خرید تتر",
"admin.treasury.plan.step.withdraw": "برداشت تتر",
"admin.treasury.plan.step.sweep": "انتقال به ارائه‌دهنده",
"admin.treasury.plan.blocked": "مسدود: {reason}",
"admin.treasury.plan.depositCap": "سقف واریز روزانه‌ی هر کد ملی: {amount}",
"admin.treasury.lots": "دسته‌های تتر (قیمت تمام‌شده)",
"admin.treasury.lot.cost": "میانگین قیمت تمام‌شده: {rate}",
"admin.treasury.fxEffect": "اثر نوسان نرخ (تحقق‌یافته و تحقق‌نیافته)",
"admin.treasury.reconcile": "تطبیق موجودی‌ها",
"admin.treasury.reconcile.ok": "موجودی‌ها با دفتر کل می‌خوانند.",
"admin.treasury.reconcile.diff": "اختلاف {amount} در {account}",
"admin.treasury.action.buy": "خرید تتر",
"admin.treasury.action.withdraw": "برداشت تتر",
"admin.treasury.action.sweep": "انتقال به ارائه‌دهنده",
"admin.treasury.action.confirm": "{action} به مقدار {qty} اجرا شود؟",
"admin.treasury.nightHalt": "بازار در ساعات محدودیت بسته است.",
"admin.treasury.providerShare": "سهم ارائه‌دهنده از موجودی: {pct}",
"admin.treasury.providerShare.high": "تمرکز بیش از حد روی یک ارائه‌دهنده",

# ── pricing editor ──
"admin.pricing.title": "ویرایش قیمت‌گذاری",
"admin.pricing.version": "نسخه‌ی فعال: {n}",
"admin.pricing.draft": "پیش‌نویس",
"admin.pricing.margin": "درصد حاشیه‌ی سود",
"admin.pricing.floorMargin": "حداقل درصد حاشیه",
"admin.pricing.minMargin": "حداقل حاشیه‌ی هر سفارش",
"admin.pricing.riskBuffer": "پوشش ریسک عملیات",
"admin.pricing.volatility": "پوشش نوسان",
"admin.pricing.lockMinutes": "مدت قفل قیمت (دقیقه)",
"admin.pricing.rounding": "گام گردکردن (تومان)",
"admin.pricing.competitor": "محافظ رقابتی",
"admin.pricing.rush": "سطوح سرعت",
"admin.pricing.vat": "مالیات بر ارزش افزوده",
"admin.pricing.paymentFees": "کارمزد روش‌های پرداخت",
"admin.pricing.family": "بر اساس گروه محصول",
"admin.pricing.preview": "پیش‌نمایش اثر",
"admin.pricing.preview.body": "با این تغییر، قیمت نمونه‌ی {product} از {old} به {new} می‌رسد.",
"admin.pricing.preview.below": "هشدار: قیمت زیر هزینه‌ی تأمین است.",
"admin.pricing.invariant": "قیمت نباید کمتر از هزینه به‌علاوه‌ی حداقل حاشیه شود.",
"admin.pricing.save": "انتشار نسخه‌ی جدید",
"admin.pricing.saved": "نسخه‌ی {n} منتشر شد.",
"admin.pricing.diff": "تفاوت با نسخه‌ی قبلی",
"admin.pricing.revert": "بازگشت به نسخه‌ی {n}",
"admin.pricing.outOfRange": "مقدار خارج از بازه‌ی مجاز ({min} تا {max}) است.",
"admin.pricing.reasonRequired": "برای هر تغییر قیمت علت ثبت کنید.",

# ── rate monitor / kill switch ──
"admin.rates.title": "نرخ‌ها",
"admin.rates.status": "وضعیت: {status}",
"admin.rates.mid": "میانه‌ی نرخ",
"admin.rates.ask": "نرخ خرید قابل‌اجرا",
"admin.rates.bid": "نرخ فروش قابل‌اجرا",
"admin.rates.spread": "اختلاف",
"admin.rates.dispersion": "پراکندگی بین صرافی‌ها",
"admin.rates.age": "قدمت آخرین نرخ: {time}",
"admin.rates.vol": "نوسان روزانه (برآوردی): {pct}",
"admin.rates.exchange": "صرافی",
"admin.rates.excluded": "حذف‌شده: {reason}",
"admin.rates.history": "تاریخچه‌ی نرخ",
"admin.rates.competitor": "قیمت رقبا",
"admin.kill.title": "کلید توقف فروش",
"admin.kill.state.off": "فروش فعال است",
"admin.kill.state.on": "فروش متوقف است",
"admin.kill.scope.all": "کل فروش",
"admin.kill.scope.product": "یک محصول",
"admin.kill.scope.rail": "یک روش پرداخت",
"admin.kill.scope.provider": "یک ارائه‌دهنده",
"admin.kill.scope.usdt": "پرداخت با تتر",
"admin.kill.activate": "توقف فروش",
"admin.kill.deactivate": "از سرگیری فروش",
"admin.kill.reason": "علت توقف",
"admin.kill.confirm": "فروش متوقف شود؟ سفارش‌های جدید پذیرفته نمی‌شود و قیمت‌های قفل‌شده تا پایان مهلت معتبرند.",
"admin.kill.confirmOff": "فروش از سر گرفته شود؟ پیش از آن نرخ‌ها و موجودی‌ها را بررسی کرده‌اید؟",
"admin.kill.auto": "توقف خودکار: {reason}",
"admin.kill.autoRule": "توقف خودکار در صورت کهنه‌شدن یا ناهمگونی نرخ بیش از {minutes} دقیقه.",
"admin.kill.banner": "کلید توقف فعال است — {reason}",

# ── catalog / customers / risk ──
"admin.catalog.title": "کاتالوگ",
"admin.catalog.active": "فعال",
"admin.catalog.riskLabel": "برچسب ریسک",
"admin.catalog.restrictionNote": "یادداشت محدودیت (نمایش به مشتری)",
"admin.catalog.restrictionRequired": "برای محصول با ریسک متوسط یا بالا ثبت یادداشت محدودیت الزامی است.",
"admin.catalog.provider": "ارائه‌دهنده‌ی اصلی",
"admin.catalog.altProviders": "ارائه‌دهندگان جایگزین",
"admin.catalog.lossLeader": "محصول جذب (اجازه‌ی حاشیه‌ی منفی)",
"admin.catalog.lossLeader.warn": "فروش زیر هزینه برای این محصول مجاز می‌شود؛ مطمئن هستید؟",
"admin.customers.title": "مشتریان",
"admin.customers.search": "جستجو با موبایل یا کد معرف",
"admin.customers.block": "مسدودسازی",
"admin.customers.unblock": "رفع مسدودی",
"admin.customers.setTier": "تغییر سطح",
"admin.customers.setLimit": "تغییر سقف",
"admin.customers.blocked": "مسدود",
"admin.customers.confirmBlock": "حساب این مشتری مسدود شود؟ سفارش‌های باز او متوقف می‌شود.",
"admin.customers.pii": "اطلاعات هویتی فقط برای نقش‌های مجاز نمایش داده می‌شود.",
"admin.risk.title": "پرچم‌های ریسک",
"admin.risk.flag.velocity": "تعداد سفارش غیرعادی",
"admin.risk.flag.failedPayments": "پرداخت‌های ناموفق مکرر",
"admin.risk.flag.thirdParty": "پرداخت از حساب شخص دیگر",
"admin.risk.flag.splitting": "الگوی تقسیم سفارش برای دور زدن سقف",
"admin.risk.flag.newAccountLarge": "حساب جدید با سفارش بزرگ",
"admin.risk.flag.chainScreen": "هشدار بررسی آدرس زنجیره‌ای",
"admin.risk.flag.referralAbuse": "الگوی سوءاستفاده از دعوت",
"admin.risk.clear": "رد هشدار (بی‌خطر)",
"admin.risk.reject": "رد سفارش و بازگشت وجه",
"admin.risk.escalate": "ارجاع به مالک",
"admin.risk.score": "امتیاز {n} از ۱۰۰",
"admin.risk.empty": "پرچم بازی وجود ندارد.",
"admin.risk.note": "تصمیم و علت در سابقه‌ی تغییرات ثبت می‌شود.",

# ── reports / audit / users / tickets / settings ──
"admin.reports.title": "گزارش‌ها",
"admin.reports.income": "صورت سود و زیان",
"admin.reports.balance": "ترازنامه",
"admin.reports.cashflow": "جریان نقدی",
"admin.reports.kpi": "شاخص‌های کلیدی",
"admin.reports.period": "بازه",
"admin.reports.basis.nominal": "اسمی (تومان)",
"admin.reports.basis.real": "واقعی (تعدیل تورمی)",
"admin.reports.basis.usd": "به دلار",
"admin.reports.export": "دریافت خروجی",
"admin.reports.empty": "برای این بازه داده‌ای وجود ندارد.",
"admin.reports.balanced": "ترازنامه متوازن است.",
"admin.reports.unbalanced": "هشدار: ترازنامه متوازن نیست.",
"admin.reports.assumptions": "مفروضات و محدودیت‌ها",
"admin.reports.notAdvice": "این گزارش مدیریتی است و جایگزین حسابرسی یا مشاوره‌ی مالیاتی نیست.",
"admin.audit.title": "سابقه‌ی تغییرات",
"admin.audit.actor": "عامل",
"admin.audit.action": "عملیات",
"admin.audit.target": "هدف",
"admin.audit.before": "پیش از تغییر",
"admin.audit.after": "پس از تغییر",
"admin.audit.reason": "علت",
"admin.audit.immutable": "این سابقه قابل ویرایش یا حذف نیست.",
"admin.audit.filter": "فیلتر",
"admin.users.title": "کاربران و دسترسی‌ها",
"admin.users.add": "افزودن کاربر",
"admin.users.role": "نقش",
"admin.users.disable": "غیرفعال‌سازی",
"admin.users.resetTotp": "بازنشانی کد دومرحله‌ای",
"admin.users.matrix": "ماتریس دسترسی",
"admin.users.lastOwner": "حداقل یک مالک باید فعال بماند.",
"admin.tickets.title": "تیکت‌ها",
"admin.tickets.assign": "اختصاص",
"admin.tickets.reply": "پاسخ",
"admin.tickets.close": "بستن تیکت",
"admin.tickets.canned": "پاسخ‌های آماده",
"admin.tickets.internalNote": "یادداشت داخلی",
"admin.settings.title": "تنظیمات",
"admin.settings.brand": "برند",
"admin.settings.hours": "ساعات کاری",
"admin.settings.flags": "پرچم‌های ویژگی",
"admin.settings.saved": "تنظیمات ذخیره شد.",
"admin.settings.restart": "برخی تنظیمات پس از بازراه‌اندازی اعمال می‌شود.",

# ── generic admin confirmations / states ──
"admin.confirm.title": "تأیید عملیات",
"admin.confirm.danger": "این عملیات حساس است و در سابقه ثبت می‌شود.",
"admin.confirm.typeToConfirm": "برای تأیید، «{word}» را بنویسید.",
"admin.confirm.word": "تأیید",
"admin.state.loading": "در حال بارگذاری…",
"admin.state.empty": "موردی برای نمایش نیست.",
"admin.state.error": "بارگذاری ممکن نشد.",
"admin.state.stale": "داده‌ها {time} پیش به‌روز شده‌اند.",
"admin.state.providerOutage": "ارائه‌دهنده {name} در دسترس نیست.",
"admin.export.csv": "دریافت CSV",
"admin.shortcut.hint": "میان‌بر: {keys}",

# ── demo simulation panel ──
"sim.title": "پنل شبیه‌ساز",
"sim.banner": "حالت نمایشی: زمان، نرخ‌ها و رویدادها شبیه‌سازی‌شده‌اند.",
"sim.now": "زمان شبیه‌سازی: {time}",
"sim.advance": "جلو بردن زمان",
"sim.advance.hour": "یک ساعت",
"sim.advance.day": "یک روز",
"sim.advance.week": "یک هفته",
"sim.speed": "سرعت",
"sim.pause": "توقف",
"sim.resume": "ادامه",
"sim.scenario": "سناریو",
"sim.scenario.apply": "اعمال سناریو",
"sim.event": "رویداد",
"sim.event.devaluation": "جهش نرخ دلار",
"sim.event.recovery": "بازگشت ارزش ریال",
"sim.event.gatewayOutage": "قطعی درگاه پرداخت",
"sim.event.exchangeHalt": "توقف بازار صرافی",
"sim.event.providerFreeze": "مسدودی ارائه‌دهنده",
"sim.event.internetShutdown": "قطع اینترنت بین‌الملل",
"sim.event.priceWar": "جنگ قیمت رقبا",
"sim.reset": "بازنشانی شبیه‌ساز",
"sim.reset.confirm": "همه‌ی داده‌های نمایشی پاک و شبیه‌ساز از ابتدا اجرا شود؟",
}
