# -*- coding: utf-8 -*-
"""Copy part 2: checkout, 3 payment methods (+wallet, bank), receipt upload, order page, card reveal."""
COPY = {
# ── checkout ──
"checkout.title": "تکمیل سفارش",
"checkout.step.review": "مرور سفارش",
"checkout.step.method": "روش پرداخت",
"checkout.step.pay": "پرداخت",
"checkout.summary.title": "خلاصه‌ی سفارش",
"checkout.summary.product": "محصول",
"checkout.summary.amount": "مبلغ اعتبار",
"checkout.summary.speed": "سرعت تحویل",
"checkout.summary.total": "مبلغ قابل پرداخت",
"checkout.method.title": "روش پرداخت را انتخاب کنید",
"checkout.method.gateway.title": "درگاه بانکی",
"checkout.method.gateway.desc": "پرداخت آنی با کارت بانکی عضو شتاب",
"checkout.method.card_to_card.title": "کارت‌به‌کارت",
"checkout.method.card_to_card.desc": "بدون کارمزد؛ پس از پرداخت، رسید را ثبت می‌کنید",
"checkout.method.usdt.title": "پرداخت با تتر (USDT)",
"checkout.method.usdt.desc": "برای کسانی که تتر در اختیار دارند؛ شبکه را با دقت انتخاب کنید",
"checkout.method.wallet.title": "کیف پول",
"checkout.method.wallet.desc": "موجودی شما: {balance}",
"checkout.method.bank_transfer.title": "انتقال بانکی (پایا/ساتنا)",
"checkout.method.bank_transfer.desc": "مناسب مبالغ بالاتر؛ تأیید ممکن است زمان‌برتر باشد",
"checkout.method.fee": "کارمزد: {amount}",
"checkout.method.noFee": "بدون کارمزد",
"checkout.method.limit": "حداکثر {amount}",
"checkout.method.unavailable.limit": "این روش برای مبلغ سفارش شما مجاز نیست (سقف {amount}).",
"checkout.method.unavailable.tier": "این روش پس از تأیید هویت فعال می‌شود.",
"checkout.method.unavailable.off": "این روش موقتاً غیرفعال است.",
"checkout.method.walletInsufficient": "موجودی کیف پول کافی نیست؛ کمبود: {amount}.",
"checkout.method.recommended": "پیشنهاد شده",
"checkout.consent.immediate": "با اجرای فوری سفارش موافقم و می‌دانم پس از تحویل، انصراف به دلیل تغییر نظر ممکن نیست.",
"checkout.consent.terms": "{terms} و {refund} را خوانده‌ام و می‌پذیرم.",
"checkout.consent.required": "برای ادامه، موارد بالا را تأیید کنید.",
"checkout.consent.highRisk": "ریسک این محصول را خوانده‌ام و می‌پذیرم؛ ممکن است حساب من توسط ارائه‌دهنده محدود شود.",
"checkout.cta.pay": "پرداخت {amount}",
"checkout.cta.continue": "ادامه",
"checkout.cta.creating": "در حال ثبت سفارش…",
"checkout.payer.title": "پرداخت باید از کارت یا حساب خودتان باشد",
"checkout.payer.body": "برای امنیت شما، فقط پرداخت از کارت یا حسابی که به نام خودتان است پذیرفته می‌شود.",
"checkout.duplicate.title": "سفارش مشابهی باز است",
"checkout.duplicate.body": "برای همین محصول یک سفارش در انتظار پرداخت دارید.",
"checkout.duplicate.view": "مشاهده‌ی سفارش باز",
"checkout.duplicate.new": "ثبت سفارش جدید",
"checkout.limit.openOrders": "تعداد سفارش‌های باز شما به سقف رسیده است ({n}).",
"checkout.limit.daily": "سقف مجاز روزانه‌ی حساب شما {limit} است.",
"checkout.error.title": "ثبت سفارش انجام نشد",
"checkout.idempotent": "این سفارش قبلاً ثبت شده است؛ آن را باز می‌کنیم.",

# ── gateway ──
"checkout.pay.gateway.title": "پرداخت از درگاه بانکی",
"checkout.pay.gateway.body": "برای پرداخت به صفحه‌ی امن بانک منتقل می‌شوید. اطلاعات کارت شما نزد ما ذخیره نمی‌شود.",
"checkout.pay.gateway.cta": "رفتن به درگاه پرداخت",
"checkout.pay.gateway.window": "تا {time} فرصت پرداخت دارید.",
"checkout.pay.gateway.verifying": "در حال تأیید پرداخت از بانک…",
"checkout.pay.gateway.verified": "پرداخت شما تأیید شد.",
"checkout.pay.gateway.cancelled": "پرداخت انجام نشد یا لغو شد. مبلغی از شما کسر نشده است؛ اگر کسر شده، حداکثر تا چند ساعت به حساب شما برمی‌گردد.",
"checkout.pay.gateway.retry": "پرداخت دوباره",
"checkout.pay.gateway.mismatch": "مبلغ پرداخت‌شده با مبلغ سفارش یکسان نیست. سفارش متوقف شد و کارشناس بررسی می‌کند.",
"checkout.pay.gateway.unreachable": "اتصال به درگاه برقرار نشد. چند لحظه بعد دوباره تلاش کنید یا روش دیگری را انتخاب کنید.",
"checkout.pay.gateway.deducted": "اگر مبلغ از حساب شما کسر شده و تأیید نشده، نیازی به پرداخت دوباره نیست؛ ظرف چند دقیقه بررسی می‌شود.",

# ── card to card ──
"checkout.pay.c2c.title": "پرداخت کارت‌به‌کارت",
"checkout.pay.c2c.step1": "مبلغ دقیق زیر را به کارت مقصد واریز کنید.",
"checkout.pay.c2c.step2": "پس از واریز، شماره‌ی پیگیری را در همین صفحه ثبت کنید.",
"checkout.pay.c2c.exactAmount": "مبلغ دقیق واریز",
"checkout.pay.c2c.exactNote": "حتماً دقیقاً همین مبلغ را واریز کنید (شامل چند تومان آخر)؛ تشخیص پرداخت شما به همین عدد وابسته است.",
"checkout.pay.c2c.destCard": "شماره‌ی کارت مقصد",
"checkout.pay.c2c.holder": "به نام",
"checkout.pay.c2c.bank": "بانک",
"checkout.pay.c2c.copyCard": "کپی شماره‌ی کارت",
"checkout.pay.c2c.copyAmount": "کپی مبلغ",
"checkout.pay.c2c.window": "مهلت پرداخت: {time}",
"checkout.pay.c2c.windowExpired": "مهلت پرداخت تمام شد. اگر واریز کرده‌اید، رسید را ثبت کنید تا بررسی شود.",
"checkout.pay.c2c.dailyCap": "سقف کارت‌به‌کارت هر کارت در روز محدود است؛ اگر مبلغ از سقف کارت شما بیشتر است، روش دیگری را انتخاب کنید.",
"checkout.pay.c2c.ownCardOnly": "واریز باید از کارتی باشد که به نام خود شما صادر شده است؛ پرداخت از کارت دیگران رد می‌شود.",
"checkout.pay.c2c.iPaid": "پرداخت کردم، ثبت رسید",
"checkout.pay.c2c.cardChanged": "شماره‌ی کارت مقصد تغییر کرده است؛ فقط به کارت نمایش‌داده‌شده در همین صفحه واریز کنید.",
"checkout.pay.c2c.warning": "هیچ‌گاه از طریق پیام یا تماس شماره‌ی کارت دیگری را نمی‌پذیرید؛ فقط همین صفحه معتبر است.",

# ── receipt ──
"receipt.title": "ثبت رسید پرداخت",
"receipt.subtitle": "برای تسریع تأیید، اطلاعات رسید را وارد کنید.",
"receipt.trackingNo": "شماره‌ی پیگیری / مرجع",
"receipt.trackingNoHelp": "شماره‌ی پیگیری روی رسید بانکی یا پیامک.",
"receipt.payerLast4": "چهار رقم آخر کارت پرداخت‌کننده",
"receipt.paidAt": "زمان پرداخت",
"receipt.image": "تصویر رسید (اختیاری)",
"receipt.image.pick": "انتخاب تصویر",
"receipt.image.limit": "فرمت jpg یا png؛ حداکثر ۵ مگابایت.",
"receipt.image.tooLarge": "حجم تصویر زیاد است؛ تصویر کوچک‌تری انتخاب کنید.",
"receipt.image.badType": "فقط تصویر jpg یا png پذیرفته می‌شود.",
"receipt.image.noCvv": "هیچ‌گاه رمز دوم یا CVV2 کارت را در تصویر نشان ندهید.",
"receipt.submit": "ثبت رسید",
"receipt.submitting": "در حال ارسال…",
"receipt.received.title": "رسید شما دریافت شد",
"receipt.received.body": "پرداخت شما در حال بررسی است. معمولاً کمتر از {time} طول می‌کشد؛ نیازی به ارسال دوباره نیست.",
"receipt.duplicate": "این شماره‌ی پیگیری قبلاً ثبت شده است.",
"receipt.invalidLast4": "چهار رقم آخر کارت را درست وارد کنید.",
"receipt.mismatch.title": "پرداخت با سفارش مطابقت ندارد",
"receipt.mismatch.body": "مبلغ یا زمان واریز با سفارش یکسان نیست. می‌توانید مابه‌التفاوت را پرداخت کنید یا با پشتیبانی صحبت کنید.",
"receipt.under.title": "مبلغ واریزی کمتر از مبلغ سفارش است",
"receipt.under.body": "کمبود: {amount}. تا پایان مهلت می‌توانید مابه‌التفاوت را واریز کنید؛ در غیر این صورت مبلغ دریافتی پس از کسر کارمزد برگردانده می‌شود.",
"receipt.under.payRest": "پرداخت مابه‌التفاوت",
"receipt.over.title": "مبلغ واریزی بیشتر از مبلغ سفارش بود",
"receipt.over.body": "مبلغ اضافی {amount} به کیف پول شما اضافه شد و برای سفارش‌های بعدی قابل استفاده است.",
"receipt.late.title": "پرداخت پس از پایان مهلت رسید",
"receipt.late.accepted": "قیمت قفل‌شده هنوز معتبر بود و سفارش شما پذیرفته شد.",
"receipt.late.requote": "نرخ تغییر کرده است. با قیمت جدید ادامه دهید یا مبلغ برگردانده شود.",
"receipt.thirdParty.title": "پرداخت از حساب شخص دیگر",
"receipt.thirdParty.body": "برای امنیت، پرداخت از کارت یا حساب دیگران پذیرفته نمی‌شود. مبلغ به صاحب حساب برمی‌گردد.",
"receipt.rejected.title": "رسید تأیید نشد",
"receipt.rejected.body": "علت: {reason}. می‌توانید اطلاعات را اصلاح و دوباره ثبت کنید.",
"receipt.attemptsLeft": "{n} بار دیگر می‌توانید رسید ثبت کنید.",

# ── usdt ──
"checkout.pay.usdt.title": "پرداخت با تتر (USDT)",
"checkout.pay.usdt.network": "شبکه",
"checkout.pay.usdt.networkWarn": "فقط روی شبکه‌ی {network} واریز کنید. واریز روی شبکه‌ی دیگر یا ارز دیگر ممکن است برای همیشه از دست برود.",
"checkout.pay.usdt.address": "آدرس کیف پول",
"checkout.pay.usdt.memo": "ممو / تگ",
"checkout.pay.usdt.memoRequired": "ثبت ممو الزامی است؛ بدون آن پرداخت شناسایی نمی‌شود.",
"checkout.pay.usdt.amount": "مبلغ دقیق",
"checkout.pay.usdt.exactNote": "همین مقدار را بفرستید. کمتر از آن به‌عنوان کم‌پرداخت بررسی می‌شود.",
"checkout.pay.usdt.copyAddress": "کپی آدرس",
"checkout.pay.usdt.qr": "نمایش کد QR",
"checkout.pay.usdt.window": "این آدرس تا {time} معتبر است.",
"checkout.pay.usdt.waiting": "منتظر دریافت واریز…",
"checkout.pay.usdt.detected": "واریز شناسایی شد؛ در انتظار تأیید شبکه ({done} از {total})",
"checkout.pay.usdt.confirmed": "واریز تأیید شد.",
"checkout.pay.usdt.txHash": "شناسه‌ی تراکنش",
"checkout.pay.usdt.screened": "برای امنیت، واریزها با فهرست‌های ریسک بررسی می‌شوند و ممکن است برخی نیازمند بررسی دستی باشند.",
"checkout.pay.usdt.wrongNetwork": "واریز روی شبکه‌ی نادرست دریافت شد. موضوع به کارشناس ارجاع شد؛ بازیابی ممکن است هزینه‌ی مشخصی داشته باشد.",
"checkout.pay.usdt.unavailable": "پرداخت با تتر برای حساب شما فعال نیست.",
"checkout.pay.usdt.tomanEquivalent": "معادل تقریبی: {amount}",
"checkout.pay.usdt.rateNote": "مبلغ تتر ثابت است؛ معادل تومانی فقط برای اطلاع نمایش داده می‌شود.",

# ── wallet pay / bank transfer ──
"checkout.pay.wallet.title": "پرداخت از کیف پول",
"checkout.pay.wallet.body": "مبلغ {amount} از موجودی کیف پول شما کسر می‌شود.",
"checkout.pay.wallet.cta": "پرداخت از کیف پول",
"checkout.pay.bank.title": "پرداخت با انتقال بانکی",
"checkout.pay.bank.iban": "شماره‌ی شبا",
"checkout.pay.bank.holder": "صاحب حساب",
"checkout.pay.bank.note": "در توضیحات واریز، شماره‌ی سفارش {code} را بنویسید.",
"checkout.pay.bank.window": "مهلت پرداخت: {time}",
"checkout.pay.bank.slow": "تأیید انتقال‌های بانکی ممکن است تا پایان چرخه‌ی بانکی طول بکشد.",

# ── order page ──
"order.title": "سفارش {code}",
"order.created": "ثبت‌شده در {time}",
"order.timeline.title": "پیگیری سفارش",
"order.timeline.created": "سفارش ثبت شد",
"order.timeline.payment": "پرداخت",
"order.timeline.paymentReview": "بررسی پرداخت",
"order.timeline.queued": "در صف انجام",
"order.timeline.fulfilling": "در حال انجام",
"order.timeline.delivered": "تحویل",
"order.timeline.completed": "تکمیل",
"order.timeline.refund": "بازگشت وجه",
"order.timeline.at": "{time}",
"order.timeline.current": "مرحله‌ی فعلی",
"order.eta.title": "زمان تقریبی تحویل",
"order.eta.value": "حدود {time} دیگر",
"order.eta.dueAt": "تا ساعت {time}",
"order.eta.queuePosition": "جایگاه شما در صف: {n}",
"order.eta.delayed": "انجام سفارش کمی بیشتر از انتظار طول کشیده است؛ از شما بابت تأخیر عذرخواهی می‌کنیم و در حال پیگیری هستیم.",
"order.eta.outsideHours": "سفارش شما خارج از ساعت کاری ثبت شد و از {time} پردازش می‌شود.",
"order.eta.waitingFunding": "تأمین اعتبار سرویس در حال انجام است؛ این مرحله ممکن است کمی طول بکشد.",
"order.pay.again": "ادامه‌ی پرداخت",
"order.pay.remaining": "{time} تا پایان مهلت پرداخت",
"order.actions.cancel": "لغو سفارش",
"order.actions.cancelConfirm": "این سفارش لغو شود؟ اگر پرداختی انجام نشده باشد، مبلغی از شما کسر نمی‌شود.",
"order.actions.confirmReceipt": "تأیید دریافت",
"order.actions.dispute": "گزارش مشکل",
"order.actions.disputeBody": "مشکل را توضیح دهید تا کارشناس بررسی کند. پیش از ارسال، جزئیات سفارش در گزارش درج می‌شود.",
"order.actions.disputeSubmit": "ثبت گزارش",
"order.actions.disputeSent": "گزارش شما ثبت شد و بررسی می‌شود.",
"order.actions.support": "گفتگو با پشتیبانی",
"order.actions.invoice": "دریافت فاکتور",
"order.actions.repeat": "سفارش دوباره",
"order.autoComplete": "اگر تا {time} اقدامی نکنید، سفارش به‌طور خودکار تکمیل می‌شود.",
"order.refund.pending": "بازگشت وجه شما ثبت شد و تا {time} به {target} واریز می‌شود.",
"order.refund.done": "مبلغ {amount} بازگردانده شد.",
"order.refund.target.card": "کارت پرداخت‌کننده",
"order.refund.target.wallet": "کیف پول شما",
"order.failed.body": "انجام این سفارش ممکن نشد. مبلغ شما برمی‌گردد یا با موافقت شما از ارائه‌دهنده‌ی دیگری تلاش می‌شود.",
"order.failed.retryOption": "تلاش دوباره از مسیر دیگر",
"order.failed.refundOption": "بازگشت وجه",
"order.hold.body": "برای امنیت شما، این سفارش به‌صورت دستی بررسی می‌شود. معمولاً کمتر از {time} طول می‌کشد و نیازی به اقدام شما نیست.",
"order.hold.mayAsk": "ممکن است برای تکمیل بررسی از شما اطلاعات بیشتری بخواهیم.",
"order.provider.outage": "ارائه‌دهنده‌ی این سرویس موقتاً با مشکل روبه‌رو است. سفارش شما در صف می‌ماند و پس از رفع مشکل انجام می‌شود؛ می‌توانید در هر زمان بازگشت وجه بگیرید.",
"order.list.title": "سفارش‌های من",
"order.list.empty.title": "هنوز سفارشی ثبت نکرده‌اید",
"order.list.empty.body": "اولین سفارش خود را از بخش محصولات ثبت کنید.",
"order.list.filter.open": "باز",
"order.list.filter.done": "تکمیل‌شده",
"order.list.filter.all": "همه",
"order.live.reconnecting": "در حال اتصال دوباره…",
"order.live.connected": "وضعیت سفارش به‌صورت زنده به‌روز می‌شود.",
"order.notFound": "این سفارش پیدا نشد یا متعلق به حساب شما نیست.",
"order.loading": "در حال بارگذاری سفارش…",
"order.offline": "آفلاین هستید؛ آخرین وضعیت ذخیره‌شده نمایش داده می‌شود.",

# ── card reveal ──
"reveal.title": "اطلاعات کارت",
"reveal.ready": "اطلاعات سفارش شما آماده است.",
"reveal.cta": "نمایش اطلاعات کارت",
"reveal.stepUp": "برای حفاظت از اطلاعات، ابتدا کد تأیید پیامکی را وارد کنید.",
"reveal.pan": "شماره‌ی کارت",
"reveal.expiry": "تاریخ انقضا",
"reveal.cvv": "کد CVV2",
"reveal.holder": "نام دارنده",
"reveal.billing": "نشانی صورت‌حساب",
"reveal.balance": "اعتبار کارت",
"reveal.copyField": "کپی {field}",
"reveal.hideIn": "نمایش اطلاعات تا {time} دیگر",
"reveal.hidden": "اطلاعات پنهان شد.",
"reveal.showAgain": "نمایش دوباره ({left} بار باقی‌مانده)",
"reveal.limitReached": "تعداد دفعات مجاز نمایش به پایان رسیده است. برای دریافت دوباره با پشتیبانی تماس بگیرید.",
"reveal.neverShare": "این اطلاعات را هرگز با کسی در میان نگذارید. پشتیبانی {brand} هیچ‌گاه CVV2 یا کد تأیید شما را نمی‌خواهد.",
"reveal.screenshotWarn": "از اطلاعات کارت تصویر نگیرید و آن را در پیام‌رسان‌ها ذخیره نکنید.",
"reveal.voucher.title": "کد هدیه",
"reveal.voucher.code": "کد",
"reveal.voucher.howTo": "نحوه‌ی استفاده",
"reveal.voucher.note": "پس از نمایش کد، فقط معیوب‌بودن کد پذیرفته می‌شود.",
"reveal.confirm.title": "اطلاعات را دریافت کردید؟",
"reveal.confirm.yes": "بله، دریافت شد",
"reveal.confirm.problem": "مشکل دارم",
"reveal.firstUse.title": "پیش از اولین استفاده",
"reveal.firstUse.body": "با مبلغ کم آزمایش کنید و شرایط فروشگاه مقصد را بررسی کنید. شرایط و محدودیت‌های ارائه‌دهنده را در افشای ریسک ببینید.",
"reveal.expiredLink": "این پیوند منقضی شده است؛ دوباره درخواست کنید.",
"reveal.error": "نمایش اطلاعات ممکن نشد. دوباره تلاش کنید.",
"reveal.audit": "هر نمایش اطلاعات در سابقه‌ی امنیتی حساب شما ثبت می‌شود.",
}
