# -*- coding: utf-8 -*-
"""Copy part 3: wallet, referral, support, KYC, legal pages, profile, errors, empty states, a11y, Mini App, PWA."""
COPY = {
# ── wallet ──
"wallet.title": "کیف پول",
"wallet.balance": "موجودی",
"wallet.explain": "کیف پول اعتباری فقط برای خرید از {brand} است و قابل برداشت یا انتقال به حساب دیگر نیست.",
"wallet.topup": "افزایش موجودی",
"wallet.topup.amount": "مبلغ افزایش",
"wallet.topup.cta": "پرداخت و افزایش موجودی",
"wallet.topup.done": "موجودی کیف پول شما افزایش یافت.",
"wallet.history.title": "تاریخچه‌ی تراکنش‌ها",
"wallet.history.empty": "هنوز تراکنشی در کیف پول ثبت نشده است.",
"wallet.history.topup": "افزایش موجودی",
"wallet.history.spend": "خرید سفارش {code}",
"wallet.history.refund": "بازگشت وجه سفارش {code}",
"wallet.history.overpay": "مبلغ اضافی پرداخت سفارش {code}",
"wallet.history.referral": "پاداش دعوت",
"wallet.noWithdraw": "برداشت از کیف پول ممکن نیست؛ بازگشت وجه به همان کارت پرداخت‌کننده انجام می‌شود.",
"wallet.error": "بارگذاری کیف پول ممکن نشد.",

# ── referral ──
"referral.title": "دعوت دوستان",
"referral.subtitle": "دوستانتان را دعوت کنید؛ پس از اولین سفارش تکمیل‌شده‌ی آن‌ها، پاداش دریافت می‌کنید.",
"referral.yourCode": "کد معرف شما",
"referral.copyLink": "کپی پیوند دعوت",
"referral.share": "اشتراک‌گذاری",
"referral.stats.invited": "دعوت‌شده",
"referral.stats.qualified": "واجد شرایط",
"referral.stats.earned": "پاداش دریافتی",
"referral.rules.title": "قوانین پاداش",
"referral.rules.one": "پاداش پس از اولین سفارش تکمیل‌شده‌ی فرد دعوت‌شده پرداخت می‌شود.",
"referral.rules.two": "هر فرد حقیقی فقط یک حساب دارد؛ ثبت‌نام چندحسابی و دعوت از خود، پاداش ندارد و حساب را مسدود می‌کند.",
"referral.rules.three": "پاداش به کیف پول شما اضافه می‌شود.",
"referral.empty": "هنوز کسی را دعوت نکرده‌اید.",
"referral.applied": "کد معرف اعمال شد.",
"referral.invalid": "این کد معرف معتبر نیست.",
"referral.self": "نمی‌توانید از کد معرف خودتان استفاده کنید.",
"referral.share.text": "با کد من در {brand} ثبت‌نام کن: {code}",

# ── support ──
"support.title": "پشتیبانی",
"support.hours": "ساعات پاسخ‌گویی: {hours}",
"support.channels.title": "راه‌های ارتباط",
"support.channels.telegram": "پشتیبانی در تلگرام",
"support.channels.bale": "پشتیبانی در بله",
"support.channels.phone": "تماس تلفنی",
"support.newTicket": "ارسال درخواست جدید",
"support.ticket.subject": "موضوع",
"support.ticket.category": "دسته‌بندی",
"support.ticket.category.payment": "پرداخت",
"support.ticket.category.delivery": "تحویل سفارش",
"support.ticket.category.card": "مشکل کارت یا کد",
"support.ticket.category.refund": "بازگشت وجه",
"support.ticket.category.account": "حساب کاربری",
"support.ticket.category.other": "سایر",
"support.ticket.order": "سفارش مرتبط",
"support.ticket.message": "پیام شما",
"support.ticket.messagePlaceholder": "مشکل را کوتاه و دقیق بنویسید. هرگز CVV2 یا رمز کارت را ارسال نکنید.",
"support.ticket.attach": "پیوست تصویر",
"support.ticket.send": "ارسال",
"support.ticket.sent": "درخواست شما ثبت شد. شماره‌ی پیگیری: {id}",
"support.ticket.firstResponse": "پاسخ اولیه معمولاً ظرف {time} ارسال می‌شود.",
"support.ticket.list.empty": "درخواستی ثبت نشده است.",
"support.ticket.status.open": "باز",
"support.ticket.status.pending": "در انتظار پاسخ شما",
"support.ticket.status.closed": "بسته‌شده",
"support.ticket.reply": "ارسال پاسخ",
"support.ticket.reopen": "بازکردن دوباره",
"support.ticket.rate": "پاسخ پشتیبانی چطور بود؟",
"support.faq.title": "پاسخ سریع",
"support.safety": "پشتیبانی {brand} هرگز رمز دوم، CVV2 یا کد پیامکی شما را نمی‌خواهد.",
"support.complaint": "اگر پاسخ ما کافی نبود، می‌توانید شکایت خود را از مسیرهای قانونی پیگیری کنید. راهنما در صفحه‌ی قوانین آمده است.",
"support.offHours": "اکنون خارج از ساعت پاسخ‌گویی هستیم؛ پیام شما در شروع ساعت کاری ({hours}) بررسی می‌شود.",

# ── KYC / identity ──
"kyc.title": "تأیید هویت",
"kyc.why": "با تأیید هویت، سقف خرید شما بالاتر می‌رود و روش‌های پرداخت بیشتری فعال می‌شود.",
"kyc.level.current": "سطح فعلی شما: {level}",
"kyc.level.limit": "سقف هر سفارش: {perOrder} — سقف ۲۴ ساعت: {perDay}",
"kyc.level.next": "با تأیید هویت به سطح «{level}» می‌رسید.",
"kyc.step.identity": "اطلاعات هویتی",
"kyc.step.card": "تأیید کارت بانکی",
"kyc.step.enhanced": "تأیید تکمیلی",
"kyc.field.fullName": "نام و نام خانوادگی",
"kyc.field.nationalId": "کد ملی",
"kyc.field.birthDate": "تاریخ تولد",
"kyc.field.phoneMatch": "شماره‌ی موبایل باید به نام خود شما ثبت شده باشد.",
"kyc.field.card": "شماره‌ی کارت بانکی به نام شما",
"kyc.consent": "اجازه می‌دهم اطلاعات هویتی من فقط برای تأیید هویت و رعایت قوانین بررسی و در حد لازم نگهداری شود.",
"kyc.consent.required": "برای ادامه، رضایت‌نامه را تأیید کنید.",
"kyc.submit": "ثبت و بررسی",
"kyc.pending.title": "اطلاعات شما در حال بررسی است",
"kyc.pending.body": "معمولاً کمتر از {time} طول می‌کشد. نتیجه را پیامک و در برنامه به شما اطلاع می‌دهیم.",
"kyc.verified.title": "هویت شما تأیید شد",
"kyc.verified.body": "سقف جدید حساب شما فعال شد.",
"kyc.rejected.title": "تأیید هویت انجام نشد",
"kyc.rejected.body": "علت: {reason}. اطلاعات را اصلاح و دوباره ثبت کنید.",
"kyc.reason.nameMismatch": "نام با کد ملی مطابقت ندارد",
"kyc.reason.phoneMismatch": "شماره‌ی موبایل به نام این کد ملی نیست",
"kyc.reason.cardMismatch": "کارت به نام این کد ملی نیست",
"kyc.reason.unclear": "اطلاعات یا تصویر خوانا نیست",
"kyc.liveness.title": "تأیید تصویری",
"kyc.liveness.body": "برای سقف‌های بالاتر، یک ویدیوی کوتاه از چهره‌ی خود ثبت می‌کنید. تصویر فقط برای تأیید هویت استفاده می‌شود.",
"kyc.privacy": "اطلاعات هویتی شما رمزگذاری و طبق سیاست حریم خصوصی نگهداری می‌شود.",
"kyc.invalidNationalId": "کد ملی معتبر نیست.",
"kyc.invalidBirth": "تاریخ تولد را به‌صورت شمسی وارد کنید (مثال: ۱۳۷۰/۰۵/۱۲).",
"kyc.tryLater": "تأیید هویت موقتاً در دسترس نیست؛ کمی بعد تلاش کنید.",
"kyc.limitReached.title": "به سقف حساب خود رسیده‌اید",
"kyc.limitReached.body": "سقف مجاز شما در این بازه {limit} است. برای افزایش سقف، هویت خود را تأیید کنید.",
"kyc.noSplit": "سقف‌ها برای هر فرد در بازه‌های زمانی تجمیع می‌شود؛ تقسیم سفارش به مبالغ کوچک‌تر راه افزایش سقف نیست.",

# ── legal ──
"legal.index.title": "قوانین و اطلاعات حقوقی",
"legal.terms.title": "شرایط استفاده",
"legal.privacy.title": "حریم خصوصی",
"legal.refund.title": "سیاست بازگشت وجه",
"legal.risk.title": "افشای ریسک",
"legal.kyc.title": "سیاست احراز هویت",
"legal.about.title": "درباره‌ی {brand}",
"legal.version": "نسخه‌ی {version} — آخرین به‌روزرسانی: {date}",
"legal.accept.title": "شرایط تغییر کرده است",
"legal.accept.body": "نسخه‌ی جدید شرایط استفاده منتشر شده است. برای ادامه، آن را بخوانید و بپذیرید.",
"legal.accept.cta": "خواندم و می‌پذیرم",
"legal.entity.title": "اطلاعات فروشنده",
"legal.entity.name": "نام حقوقی: {value}",
"legal.entity.regNo": "شماره‌ی ثبت: {value}",
"legal.entity.econCode": "کد اقتصادی: {value}",
"legal.entity.address": "نشانی: {value}",
"legal.entity.contact": "تماس: {value}",
"legal.notLawAdvice": "این متن جایگزین مشاوره‌ی حقوقی نیست.",
"legal.complaints.title": "ثبت شکایت",
"legal.complaints.body": "ابتدا از طریق پشتیبانی پیگیری کنید. در صورت نبود نتیجه، مراجع رسیدگی به شکایات مصرف‌کنندگان را می‌توانید پیگیری کنید.",
"legal.missing": "این صفحه هنوز منتشر نشده است.",

# ── profile / settings ──
"profile.title": "حساب من",
"profile.name": "نام",
"profile.phone": "شماره‌ی موبایل",
"profile.level": "سطح حساب",
"profile.language": "زبان",
"profile.theme": "پوسته",
"profile.notifications": "اعلان‌ها",
"profile.notifications.telegram": "اعلان در تلگرام",
"profile.notifications.bale": "اعلان در بله",
"profile.notifications.sms": "پیامک وضعیت‌های مهم",
"profile.notifications.email": "ایمیل",
"profile.notifications.sms.locked": "پیامک کدهای تأیید و رویدادهای امنیتی همیشه ارسال می‌شود.",
"profile.security": "امنیت",
"profile.sessions": "نشست‌های فعال",
"profile.logoutAll": "خروج از همه‌ی دستگاه‌ها",
"profile.delete": "درخواست حذف حساب",
"profile.deleteNote": "برخی اطلاعات تراکنش‌ها طبق قانون باید نگهداری شود.",
"profile.saved": "تغییرات ذخیره شد.",
"profile.exportData": "دریافت اطلاعات من",

# ── errors (AppErrorCode) ──
"error.VALIDATION": "اطلاعات واردشده درست نیست. موارد مشخص‌شده را اصلاح کنید.",
"error.UNAUTHENTICATED": "برای ادامه وارد حساب خود شوید.",
"error.FORBIDDEN": "دسترسی به این بخش برای شما مجاز نیست.",
"error.NOT_FOUND": "مورد درخواستی پیدا نشد.",
"error.CONFLICT": "این مورد هم‌زمان توسط شخص دیگری تغییر کرد. صفحه را تازه کنید.",
"error.RATES_UNAVAILABLE": "نرخ‌ها موقتاً در دسترس نیستند؛ لحظاتی بعد دوباره تلاش کنید.",
"error.KILL_SWITCH": "ثبت سفارش جدید موقتاً متوقف است. سفارش‌های قبلی شما ادامه می‌یابد.",
"error.QUOTE_EXPIRED": "قفل قیمت تمام شده است. قیمت تازه را مشاهده کنید.",
"error.PRODUCT_UNAVAILABLE": "این محصول در حال حاضر در دسترس نیست.",
"error.LIMIT_EXCEEDED": "مبلغ یا تعداد سفارش از سقف مجاز حساب شما بیشتر است.",
"error.ORDER_INVALID_TRANSITION": "این اقدام در وضعیت فعلی سفارش ممکن نیست.",
"error.PAYMENT_MISMATCH": "پرداخت با سفارش مطابقت ندارد و برای بررسی به کارشناس ارجاع شد.",
"error.PAYMENT_METHOD_UNAVAILABLE": "این روش پرداخت اکنون در دسترس نیست؛ روش دیگری را انتخاب کنید.",
"error.RATE_LIMITED": "تعداد درخواست‌ها زیاد بود. کمی صبر کنید و دوباره تلاش کنید.",
"error.PROVIDER_ERROR": "ارائه‌دهنده‌ی سرویس موقتاً پاسخ نمی‌دهد. سفارش شما از دست نمی‌رود.",
"error.INSUFFICIENT_FUNDS": "موجودی کافی نیست.",
"error.RUSH_UNAVAILABLE": "ظرفیت این سرعت تحویل پر شده است؛ سرعت دیگری را انتخاب کنید.",
"error.INTERNAL": "خطای داخلی رخ داد. اگر تکرار شد، شناسه‌ی درخواست را برای پشتیبانی بفرستید.",
"error.requestId": "شناسه‌ی درخواست: {id}",
"error.retryable": "این مشکل موقتی است؛ دوباره تلاش کنید.",
"error.contactSupport": "اگر مشکل ادامه داشت، با پشتیبانی تماس بگیرید.",
"error.paymentSafe": "اگر مبلغی کسر شده، از دست نمی‌رود؛ پرداخت شما بررسی و در صورت نیاز برگردانده می‌شود.",

# ── empty states / misc ──
"empty.notifications": "اعلان تازه‌ای ندارید.",
"empty.tickets": "درخواستی ثبت نشده است.",
"empty.search": "نتیجه‌ای برای «{q}» پیدا نشد.",
"notifications.title": "اعلان‌ها",
"notifications.markAllRead": "علامت‌گذاری همه به‌عنوان خوانده‌شده",
"notifications.unread": "{n} اعلان خوانده‌نشده",

# ── accessibility labels ──
"a11y.menu": "باز کردن منو",
"a11y.closeDialog": "بستن پنجره",
"a11y.copyValue": "کپی {label}",
"a11y.countdown": "زمان باقی‌مانده: {time}",
"a11y.progress": "مرحله‌ی {current} از {total}",
"a11y.loading": "در حال بارگذاری",
"a11y.priceUpdated": "قیمت به‌روز شد: {amount}",
"a11y.sheetHandle": "بستن با کشیدن به پایین",
"a11y.riskLevel": "سطح ریسک: {level}",
"a11y.externalLink": "باز می‌شود در پنجره‌ی جدید",
"a11y.liveStatus": "وضعیت سفارش: {status}",
"a11y.toggleTheme": "تغییر پوسته",
"a11y.ltrValue": "مقدار لاتین: {value}",

# ── Mini App specifics ──
"miniapp.welcome.title": "به {brand} خوش آمدید",
"miniapp.welcome.body": "همین‌جا سفارش دهید، پرداخت کنید و وضعیت را پیگیری کنید.",
"miniapp.auth.auto": "با حساب {host} شما وارد می‌شوید.",
"miniapp.auth.phoneNeeded": "برای ثبت سفارش، شماره‌ی موبایل خود را تأیید کنید.",
"miniapp.auth.sharePhone": "اشتراک شماره‌ی موبایل",
"miniapp.auth.declined": "اشتراک شماره انجام نشد؛ می‌توانید شماره را دستی وارد کنید.",
"miniapp.payment.external": "برای پرداخت، صفحه‌ی بانک در مرورگر باز می‌شود. پس از پرداخت به همین برنامه برگردید.",
"miniapp.payment.returned": "خوش برگشتید؛ وضعیت پرداخت را بررسی می‌کنیم.",
"miniapp.closeConfirm": "سفارش شما هنوز تکمیل نشده است. خارج می‌شوید؟",
"miniapp.deeplink.order": "سفارش {code}",
"miniapp.deeplink.product": "محصول {product}",
"miniapp.deeplink.invalid": "این پیوند معتبر نیست؛ به صفحه‌ی اصلی می‌رویم.",
"miniapp.share.button": "ارسال به دوستان",
"miniapp.update": "نسخه‌ی تازه‌ای در دسترس است. برای دیدن آن، برنامه را ببندید و دوباره باز کنید.",
"miniapp.unsupported": "این قابلیت در نسخه‌ی فعلی {host} پشتیبانی نمی‌شود؛ از وب‌سایت استفاده کنید.",
"miniapp.openWeb": "باز کردن در وب‌سایت",
"miniapp.keyboardTip": "برای ادامه، دکمه‌ی پایین صفحه را بزنید.",

# ── PWA / connectivity ──
"pwa.install.title": "نصب برنامه",
"pwa.install.body": "برای دسترسی سریع‌تر، {brand} را به صفحه‌ی اصلی اضافه کنید.",
"pwa.install.cta": "افزودن به صفحه‌ی اصلی",
"pwa.install.later": "بعداً",
"pwa.update.available": "نسخه‌ی تازه آماده است.",
"pwa.update.cta": "به‌روزرسانی",
"pwa.offline.cached": "آخرین اطلاعات ذخیره‌شده نمایش داده می‌شود ({time}).",
"pwa.offline.checkoutBlocked": "برای ثبت سفارش یا پرداخت باید آنلاین باشید.",
"pwa.slow": "اتصال کند است؛ در حال تلاش دوباره…",
"pwa.dataSaver": "حالت صرفه‌جویی در داده فعال است؛ تصاویر غیرضروری بارگذاری نمی‌شود.",
}
