#!/usr/bin/env node
// Generates src/styles/tokens.css from design tokens.
// Source: docs/05-architecture/design-tokens.json (UX specialist) when present AND in the supported shape; else src/styles/tokens.default.json.
// Supported shape: { color: { light: {name: "#hex"}, dark: {...} }, radius: {...}, shadow: { light: {...}, dark: {...} } }
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const webRoot = path.resolve(here, '..')
const uxFile = path.resolve(webRoot, '../../docs/05-architecture/design-tokens.json')
const defFile = path.resolve(webRoot, 'src/styles/tokens.default.json')

const def = JSON.parse(fs.readFileSync(defFile, 'utf8'))
let src = def
let used = 'tokens.default.json'
if (fs.existsSync(uxFile)) {
  try {
    const ux = JSON.parse(fs.readFileSync(uxFile, 'utf8'))
    if (ux?.color?.light && ux?.color?.dark) {
      // merge over defaults so missing names never break the build
      src = {
        ...def,
        ...ux,
        color: { light: { ...def.color.light, ...ux.color.light }, dark: { ...def.color.dark, ...ux.color.dark } },
        radius: { ...def.radius, ...(ux.radius ?? {}) },
        shadow: ux.shadow ?? def.shadow,
      }
      used = 'docs/05-architecture/design-tokens.json (merged over defaults)'
    }
  } catch (e) {
    console.warn('[gen-tokens] could not parse UX tokens, using defaults:', e.message)
  }
}

const hexToTriplet = (hex) => {
  const h = hex.replace('#', '')
  const full = h.length === 3 ? [...h].map((c) => c + c).join('') : h
  const n = parseInt(full.slice(0, 6), 16)
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`
}
const colorVars = (obj) => Object.entries(obj).map(([k, v]) => `  --c-${k}: ${hexToTriplet(v)};`).join('\n')
const radiusVars = Object.entries(src.radius).map(([k, v]) => `  --r-${k}: ${v};`).join('\n')
const shadowVars = (obj) => Object.entries(obj).map(([k, v]) => `  --shadow-${k}: ${v};`).join('\n')

const css = `/* GENERATED by scripts/gen-tokens.mjs from ${used} — do not edit. */
:root {
${colorVars(src.color.light)}
${radiusVars}
${shadowVars(src.shadow.light)}
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${colorVars(src.color.dark).replace(/^ {2}/gm, '    ')}
${shadowVars(src.shadow.dark).replace(/^ {2}/gm, '    ')}
    color-scheme: dark;
  }
}
:root[data-theme='dark'] {
${colorVars(src.color.dark)}
${shadowVars(src.shadow.dark)}
  color-scheme: dark;
}
`
fs.writeFileSync(path.resolve(webRoot, 'src/styles/tokens.css'), css)
console.log(`[gen-tokens] wrote src/styles/tokens.css from ${used}`)
