#!/usr/bin/env node
// Generates src/copy/fa.ts (typed, `as const`) from:
//   1. src/copy/deck/*.json   — the web app's own copy deck (namespaces = file names), written by B7a
//   2. data/copy.fa.json      — the UX specialist's deck, when present: its `web` (or `ui`) namespace is deep-merged OVER ours
// Never hard-code UI text in components: add a key to a deck file, rerun `npm run gen:copy -w @hiclaude/web`, use t('ns.key').
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const webRoot = path.resolve(here, '..')
const deckDir = path.resolve(webRoot, 'src/copy/deck')
const uxFile = path.resolve(webRoot, '../../data/copy.fa.json')

const isObj = (v) => v && typeof v === 'object' && !Array.isArray(v)
const merge = (a, b) => {
  const out = { ...a }
  for (const [k, v] of Object.entries(b)) out[k] = isObj(v) && isObj(out[k]) ? merge(out[k], v) : v
  return out
}

let deck = {}
for (const f of fs.readdirSync(deckDir).filter((f) => f.endsWith('.json')).sort()) {
  const ns = f.replace(/\.json$/, '')
  deck[ns] = JSON.parse(fs.readFileSync(path.join(deckDir, f), 'utf8'))
}

let source = 'src/copy/deck/*.json'
if (fs.existsSync(uxFile)) {
  try {
    const ux = JSON.parse(fs.readFileSync(uxFile, 'utf8'))
    const web = ux.web ?? ux.ui
    if (isObj(web)) {
      deck = merge(deck, web)
      source += ' + data/copy.fa.json#' + (ux.web ? 'web' : 'ui')
    }
  } catch (e) {
    console.warn('[gen-copy] could not parse data/copy.fa.json:', e.message)
  }
}

const out = `/* GENERATED by scripts/gen-copy.mjs from ${source} — do not edit by hand. */
export const fa = ${JSON.stringify(deck, null, 2)} as const
`
fs.writeFileSync(path.resolve(webRoot, 'src/copy/fa.ts'), out)
console.log(`[gen-copy] wrote src/copy/fa.ts from ${source}`)
