import { describe, expect, it } from 'vitest'
import { MS, createRng, fromIrst } from '@hiclaude/contracts'
import { DecisionLog, DecisionSchedule, OwnerPolicy, OwnerDecisionSchema, applyDecisionsFile, buildDigest, conflictKey, describeDecision, loadPolicyConfig, mergeDecisionStreams, parseDecision, parseDecisionBody, parseDecisionsFile, rankIssues, writeDecisionLog, type OwnerDecisionBody, type PolicyDecision } from './index'
import { DECISION_TYPES } from './decisions'
import { fuzzObs, makeObs } from './testing'
import { readFileSync, mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const find = (ds: PolicyDecision[], type: string) => ds.filter((d) => d.decision.type === type)
/** run the policy for n days with obs generated by fn(day) and collect decisions by day */
const run = (p: OwnerPolicy, days: number, fn: (d: number) => ReturnType<typeof makeObs>) => {
  const all: Array<{ day: number; d: PolicyDecision }> = []
  for (let day = 0; day < days; day++) for (const d of p.decide(fn(day))) all.push({ day, d })
  return all
}

describe('decision schema', () => {
  it('accepts every decision type from the brief', () => {
    const ok: unknown[] = [
      { date: '2027-01-01', type: 'set_margin', family: 'ai_subscription', marginPct: 0.14 },
      { date: '2027-01-01', type: 'set_buffers', volatilityMinBufferPct: 0.02 },
      { date: '2027-01-01', type: 'set_rush', tier: 'express', premiumPct: 0.3, minPremiumIrt: 50000, capacityPerHour: 4 },
      { date: '2027-01-01', type: 'set_target_coverage', days: 7 },
      { date: '2027-01-01', type: 'hire_operator', count: 2, shift: 'night' },
      { date: '2027-01-01', type: 'fire_operator' },
      { date: '2027-01-01', type: 'set_marketing_budget', monthlyIrt: 50_000_000, mix: { seo: 1 } },
      { date: '2027-01-01', type: 'capital_injection', irt: 100_000_000 },
      { date: '2027-01-01', type: 'owner_draw', irt: 10_000_000 },
      { date: '2027-01-01', type: 'switch_provider', family: 'virtual_card', providerId: 'altcard' },
      { date: '2027-01-01', type: 'switch_provider', productId: 'vcard-new', providerId: 'altcard' },
      { date: '2027-01-01', type: 'set_product_active', productId: 'x', active: false },
      { date: '2027-01-01', type: 'set_risk_limits', holdScoreThreshold: 60 },
      { date: '2027-01-01', type: 'run_promotion', family: 'gift_card', discountPct: 0.05, days: 7 },
      { date: '2027-01-01', type: 'kill_switch', on: true, reason: 'test' },
      { date: '2027-01-01', type: 'pay_tax', kind: 'vat', irt: 1_000_000 },
    ]
    expect(ok.length).toBe(DECISION_TYPES.length + 1) // switch_provider twice
    for (const x of ok) expect(() => parseDecision(x)).not.toThrow()
    expect(parseDecision({ date: '2027-01-01', type: 'fire_operator' })).toMatchObject({ count: 1 })
  })
  it('rejects bad dates, unknown types, bad ranges and empty refinements', () => {
    expect(() => parseDecision({ date: '2027-02-30', type: 'set_target_coverage', days: 3 })).toThrow(/date/)
    expect(() => parseDecision({ date: '27-01-01', type: 'set_target_coverage', days: 3 })).toThrow()
    expect(() => parseDecision({ date: '2027-01-01', type: 'launch_rocket' })).toThrow(/unknown decision type/)
    expect(() => parseDecision({ date: '2027-01-01', type: 'set_margin', family: 'a', marginPct: 1.5 })).toThrow()
    expect(() => parseDecision({ date: '2027-01-01', type: 'hire_operator', count: 0, shift: 'night' })).toThrow()
    expect(() => parseDecision({ date: '2027-01-01', type: 'hire_operator', count: 1, shift: 'noon' })).toThrow()
    expect(() => parseDecision({ date: '2027-01-01', type: 'set_buffers' })).toThrow(/at least one/)
    expect(() => parseDecision({ date: '2027-01-01', type: 'switch_provider', providerId: 'p' })).toThrow(/exactly one/)
    expect(() => parseDecision({ date: '2027-01-01', type: 'run_promotion', family: 'g', discountPct: 0.9, days: 3 })).toThrow()
    expect(() => parseDecision({ date: '2027-01-01', type: 'capital_injection', irt: 0 })).toThrow()
    expect(() => parseDecision({ date: '2027-01-01', type: 'owner_draw', irt: 1.5 })).toThrow()
  })
  it('body parser does not need a date; exported zod schemas validate too', () => {
    expect(parseDecisionBody({ type: 'set_target_coverage', days: 4 })).toEqual({ type: 'set_target_coverage', days: 4 })
    expect(OwnerDecisionSchema.safeParse({ date: '2027-01-01', type: 'set_target_coverage', days: 4 }).success).toBe(true)
    expect(OwnerDecisionSchema.safeParse({ type: 'set_target_coverage', days: 4 }).success).toBe(false)
  })
  it('decision file: array or {decisions}, sorted by date (stable), errors name the index', () => {
    const a = { date: '2027-03-01', type: 'set_target_coverage', days: 3 }
    const b = { date: '2027-01-01', type: 'set_target_coverage', days: 6 }
    const c = { date: '2027-01-01', type: 'set_target_coverage', days: 9 }
    expect(parseDecisionsFile([a, b, c]).map((d) => (d as { days: number }).days)).toEqual([6, 9, 3])
    expect(parseDecisionsFile({ decisions: [a] })).toHaveLength(1)
    expect(() => parseDecisionsFile([a, { date: 'x', type: 'set_margin' }])).toThrow(/decision #1/)
    expect(() => parseDecisionsFile('nope')).toThrow()
  })
  it('conflict keys group levers and describeDecision is total', () => {
    expect(conflictKey({ type: 'hire_operator', count: 1, shift: 'night' })).toBe(conflictKey({ type: 'fire_operator', count: 1 }))
    expect(conflictKey({ type: 'set_margin', family: 'a', marginPct: 0.1 })).not.toBe(conflictKey({ type: 'set_margin', family: 'b', marginPct: 0.1 }))
    for (const d of [{ type: 'set_margin', family: 'a', marginPct: 0.1 }, { type: 'kill_switch', on: true, reason: 'r' }, { type: 'set_risk_limits', holdScoreThreshold: 50 }] as OwnerDecisionBody[]) expect(describeDecision(d).length).toBeGreaterThan(3)
  })
})

describe('DecisionSchedule', () => {
  const file = [
    { date: '2026-10-05', type: 'set_target_coverage', days: 7 },
    { date: '2026-10-10', type: 'set_margin', family: 'gift_card', marginPct: 0.1 },
    { date: '2026-10-10', type: 'owner_draw', irt: 5_000_000 },
  ]
  it('releases each decision once at its IRST date', () => {
    const s = DecisionSchedule.fromFile(file)
    expect(s.popDue(fromIrst(2026, 10, 4, 23, 59))).toHaveLength(0)
    expect(s.popDue(fromIrst(2026, 10, 5, 0, 0))).toHaveLength(1)
    expect(s.popDue(fromIrst(2026, 10, 7))).toHaveLength(0)
    expect(s.popDue(fromIrst(2026, 10, 20)).map((d) => d.type)).toEqual(['set_margin', 'owner_draw'])
    expect(s.popDue(fromIrst(2026, 12, 1))).toHaveLength(0)
    expect(s.pending).toBe(0)
  })
  it('nextAt and size', () => {
    const s = DecisionSchedule.fromFile(file)
    expect(s.size).toBe(3)
    expect(s.nextAt()).toBe(fromIrst(2026, 10, 5))
  })
  it('applyDecisionsFile helper is idempotent through the applied set', () => {
    const applied = new Set<number>()
    expect(applyDecisionsFile(file, fromIrst(2026, 10, 6), applied)).toHaveLength(1)
    expect(applyDecisionsFile(file, fromIrst(2026, 10, 6), applied)).toHaveLength(0)
    expect(applyDecisionsFile(file, fromIrst(2026, 10, 11), applied)).toHaveLength(2)
  })
  it('catch-up: a late call releases everything that is overdue, in order', () => {
    const s = DecisionSchedule.fromFile(file)
    expect(s.popDue(fromIrst(2027, 1, 1)).map((d) => d.date)).toEqual(['2026-10-05', '2026-10-10', '2026-10-10'])
  })
  it('merge: file decisions win on the same lever; policy decisions on other levers survive', () => {
    const pol: PolicyDecision[] = [
      { decision: { type: 'set_margin', family: 'gift_card', marginPct: 0.11 }, rule: 'r', rationale: '', kpiSeen: {} },
      { decision: { type: 'set_margin', family: 'cloud', marginPct: 0.11 }, rule: 'r', rationale: '', kpiSeen: {} },
    ]
    const f = parseDecisionsFile([{ date: '2026-10-10', type: 'set_margin', family: 'gift_card', marginPct: 0.2 }])
    const m = mergeDecisionStreams(pol, f)
    expect(m.suppressed).toHaveLength(1)
    expect(m.merged.map((x) => x.source)).toEqual(['file', 'policy'])
    expect((m.merged[0]!.decision as { marginPct: number }).marginPct).toBe(0.2)
  })
  it('policy stays away from levers the file touched (observeExternal lock)', () => {
    const p = new OwnerPolicy({ preset: 'baseline' })
    p.observeExternal({ type: 'set_margin', family: 'gift_card', marginPct: 0.2 }, fromIrst(2026, 10, 3), 30)
    const out = run(p, 20, (d) => makeObs(d, { families: { gift_card: { orders: 10, quotes: 400, conversionRate: 0.6, marginPct: 0.2 } } }))
    expect(out.filter((x) => x.d.decision.type === 'set_margin')).toHaveLength(0)
  })
})

describe('DecisionLog + digest', () => {
  it('records policy and file decisions with summaries and counts', () => {
    const log = new DecisionLog()
    log.record(1, '2026-10-03', 'file', { type: 'set_target_coverage', days: 6, rationale: 'persona' })
    log.recordPolicy(2, '2026-10-04', { decision: { type: 'owner_draw', irt: 1_000_000 }, rule: 'treasury.draw', rationale: 'why', kpiSeen: { cash: 1 } }, true)
    expect(log.all).toHaveLength(2)
    expect(log.all[0]!.rationale).toBe('persona')
    expect(log.all[1]!.seq).toBe(2)
    expect(log.countByType()).toEqual({ set_target_coverage: 1, owner_draw: 1 })
    expect(log.last(1)[0]!.rule).toBe('treasury.draw')
    expect(log.toJSON().schema).toContain('decisions')
  })
  it('writes decisions.log.json', () => {
    const dir = mkdtempSync(join(tmpdir(), 'dlog-'))
    const log = new DecisionLog()
    log.record(1, '2026-10-03', 'manual', { type: 'kill_switch', on: false, reason: 'x' })
    writeDecisionLog(join(dir, 'sub', 'decisions.log.json'), log)
    expect(JSON.parse(readFileSync(join(dir, 'sub', 'decisions.log.json'), 'utf8')).entries).toHaveLength(1)
  })
  it('digest has the headline blocks, deltas, ranked issues and last decisions', () => {
    const log = new DecisionLog()
    for (let i = 0; i < 12; i++) log.record(i, '2026-10-03', 'policy', { type: 'set_target_coverage', days: 5 })
    const obs = makeObs(10, { kpi: { slaAttainment: 0.7, queueAgeP90Min: 300 }, cash: { cashIrt: 10_000_000, burnPerDayIrt: 1_000_000, runwayDays: 10, opexPerMonthIrt: 100_000_000 }, alerts: [{ code: 'x', severity: 'warning', message: 'm' }] })
    obs.prevKpi = { ...obs.kpi, orders: 50 }
    const d = buildDigest(obs, log.all)
    expect(d.schema).toBe('hiclaude.digest/1')
    expect(d.kpis.deltaPct.orders).toBe(1)
    expect(d.lastDecisions).toHaveLength(10)
    expect(d.topIssues[0]!.severity).toBe('critical')
    expect(d.topIssues.some((i) => i.code === 'sla.low')).toBe(true)
    expect(d.headlineFa).toMatch(/[۰-۹]/)
    expect(d.cash.runwayDays).toBe(10)
    expect(JSON.parse(JSON.stringify(d)).asOf).toBe(obs.date)
  })
  it('infinite runway is serialised as null; issues capped', () => {
    const d = buildDigest(makeObs(1), [])
    expect(d.cash.runwayDays).toBeNull()
    expect(rankIssues(makeObs(1)).length).toBeLessThanOrEqual(8)
  })
})

describe('policy presets', () => {
  it('the three presets load and are ordered by risk appetite', () => {
    const c = loadPolicyConfig('conservative')
    const b = loadPolicyConfig('baseline')
    const a = loadPolicyConfig('aggressive')
    expect(c.treasury.baseCoverageDays).toBeGreaterThan(b.treasury.baseCoverageDays)
    expect(b.treasury.baseCoverageDays).toBeGreaterThan(a.treasury.baseCoverageDays)
    expect(a.marketing.budgetShareOfCash).toBeGreaterThan(b.marketing.budgetShareOfCash)
    expect(c.pricing.floorMarginPct).toBeGreaterThan(a.pricing.floorMarginPct)
  })
  it('overrides deep-merge and are validated', () => {
    expect(loadPolicyConfig('baseline', { pricing: { marginStepPct: 0.02 } }).pricing.marginStepPct).toBe(0.02)
    expect(loadPolicyConfig('baseline', { pricing: { marginStepPct: 0.02 } }).pricing.winRateLow).toBe(loadPolicyConfig('baseline').pricing.winRateLow)
    expect(() => loadPolicyConfig('baseline', { pricing: { marginStepPct: 'x' as unknown as number } })).toThrow()
  })
})

describe('policy rules', () => {
  it('no decisions on day 0 and none in a healthy steady state (cadenced rules start their clock)', () => {
    const p = new OwnerPolicy()
    expect(p.decide(makeObs(0))).toHaveLength(0)
  })
  it('pricing: winning too much ⇒ margin up by one bounded step; losing ⇒ margin down', () => {
    const cfg = loadPolicyConfig('baseline')
    const p = new OwnerPolicy()
    const out = run(p, 9, (d) => makeObs(d, { families: { gift_card: { orders: 150, quotes: 400, conversionRate: 0.5, marginPct: 0.1 }, virtual_card: { orders: 10, quotes: 400, conversionRate: 0.04, marginPct: 0.12 } } }))
    const up = out.find((x) => x.d.decision.type === 'set_margin' && (x.d.decision as { family: string }).family === 'gift_card')!
    const dn = out.find((x) => x.d.decision.type === 'set_margin' && (x.d.decision as { family: string }).family === 'virtual_card')!
    expect((up.d.decision as { marginPct: number }).marginPct).toBeCloseTo(0.1 + cfg.pricing.marginStepPct, 9)
    expect((dn.d.decision as { marginPct: number }).marginPct).toBeCloseTo(0.12 - cfg.pricing.marginStepPct, 9)
    expect(up.d.rationale).toContain('win rate')
  })
  it('pricing: within the band nothing changes; too few quotes ⇒ no decision', () => {
    const p = new OwnerPolicy()
    expect(run(p, 30, (d) => makeObs(d, { families: { a: { orders: 5, quotes: 100, conversionRate: 0.22, marginPct: 0.1 } } })).filter((x) => x.d.decision.type === 'set_margin')).toHaveLength(0)
    const q = new OwnerPolicy()
    expect(run(q, 30, (d) => makeObs(d, { families: { a: { orders: 5, quotes: 10, conversionRate: 0.9, marginPct: 0.1 } } })).filter((x) => x.d.decision.type === 'set_margin')).toHaveLength(0)
  })
  it('pricing: respects floor/ceiling and the cumulative 30-day bound', () => {
    const cfg = loadPolicyConfig('baseline')
    const p = new OwnerPolicy()
    let m = 0.1
    const moves: number[] = []
    for (let day = 0; day < 60; day++) {
      for (const d of p.decide(makeObs(day, { families: { a: { orders: 100, quotes: 300, conversionRate: 0.7, marginPct: m } } }))) {
        if (d.decision.type === 'set_margin') {
          moves.push(d.decision.marginPct - m)
          m = d.decision.marginPct
        }
      }
    }
    expect(m).toBeLessThanOrEqual(cfg.pricing.maxMarginPct + 1e-9)
    expect(moves.length).toBeGreaterThan(2)
    for (const mv of moves) expect(Math.abs(mv)).toBeLessThanOrEqual(cfg.pricing.maxMarginStepPerDecisionPct + 1e-9)
    // rolling 30d net move bounded
    expect(0.1 + cfg.pricing.maxCumulative30dPct + cfg.pricing.maxCumulative30dPct).toBeGreaterThanOrEqual(m - 1e-9)
    const floorP = new OwnerPolicy()
    let fm = 0.045
    for (let day = 0; day < 60; day++) for (const d of floorP.decide(makeObs(day, { families: { a: { orders: 1, quotes: 300, conversionRate: 0.01, marginPct: fm } } }))) if (d.decision.type === 'set_margin') fm = d.decision.marginPct
    expect(fm).toBeGreaterThanOrEqual(cfg.pricing.floorMarginPct - 1e-9)
  })
  it('pricing: capacity stress nudges margin up even inside the band', () => {
    const p = new OwnerPolicy()
    const out = run(p, 14, (d) => makeObs(d, { kpi: { queueAgeP90Min: 400, slaAttainment: 0.6 }, families: { a: { orders: 5, quotes: 300, conversionRate: 0.2, marginPct: 0.1 } } }))
    expect(out.some((x) => x.d.decision.type === 'set_margin' && (x.d.decision as { marginPct: number }).marginPct > 0.1)).toBe(true)
  })
  it('staffing: hires only after k consecutive breach days, on the thinnest shift, then cools down', () => {
    const cfg = loadPolicyConfig('baseline')
    const p = new OwnerPolicy()
    const out = run(p, 30, (d) => makeObs(d, { kpi: { queueAgeP90Min: 400 }, staff: { operators: 3, byShift: { morning: 2, evening: 1, night: 0 } } }))
    const hires = out.filter((x) => x.d.decision.type === 'hire_operator')
    expect(hires.length).toBeGreaterThanOrEqual(1)
    expect(hires[0]!.day).toBe(cfg.staffing.queueAgeBreachDaysToHire - 1)
    expect((hires[0]!.d.decision as { shift: string }).shift).toBe('night')
    for (let i = 1; i < hires.length; i++) expect(hires[i]!.day - hires[i - 1]!.day).toBeGreaterThanOrEqual(cfg.staffing.cooldownDaysAfterHire)
  })
  it('staffing: a good day resets the breach counter (no flapping hires)', () => {
    const p = new OwnerPolicy()
    const out = run(p, 40, (d) => makeObs(d, { kpi: { queueAgeP90Min: d % 3 === 2 ? 20 : 400 } }))
    expect(out.filter((x) => x.d.decision.type === 'hire_operator')).toHaveLength(0)
  })
  it('staffing: no hiring beyond max operators or when cash runway is critical', () => {
    const maxed = new OwnerPolicy()
    expect(run(maxed, 20, (d) => makeObs(d, { kpi: { queueAgeP90Min: 500 }, staff: { operators: 24, byShift: { morning: 8, evening: 8, night: 8 } } })).filter((x) => x.d.decision.type === 'hire_operator')).toHaveLength(0)
    const broke = new OwnerPolicy()
    expect(run(broke, 20, (d) => makeObs(d, { kpi: { queueAgeP90Min: 500 }, cash: { cashIrt: 1_000_000, burnPerDayIrt: 1_000_000, runwayDays: 1, opexPerMonthIrt: 1e8 } })).filter((x) => x.d.decision.type === 'hire_operator')).toHaveLength(0)
  })
  it('staffing: fires one operator after sustained low utilisation, never below the minimum, never right after a hire', () => {
    const cfg = loadPolicyConfig('baseline')
    const p = new OwnerPolicy()
    const out = run(p, 80, (d) => makeObs(d, { kpi: { operatorUtilisation: 0.1, queueAgeP90Min: 5 }, staff: { operators: 4, byShift: { morning: 2, evening: 1, night: 1 } } }))
    const fires = out.filter((x) => x.d.decision.type === 'fire_operator')
    expect(fires.length).toBeGreaterThanOrEqual(1)
    expect(fires[0]!.day).toBeGreaterThanOrEqual(cfg.staffing.lowUtilisationWeeksToFire * 7 - 1)
    const atMin = new OwnerPolicy()
    expect(run(atMin, 80, (d) => makeObs(d, { kpi: { operatorUtilisation: 0.05 }, staff: { operators: cfg.staffing.minOperators, byShift: { morning: 1, evening: 1, night: 0 } } })).filter((x) => x.d.decision.type === 'fire_operator')).toHaveLength(0)
  })
  it('staffing hysteresis: never hires and fires in the same run of observations back-to-back', () => {
    const p = new OwnerPolicy()
    const out = run(p, 200, (d) => makeObs(d, { kpi: { queueAgeP90Min: d % 40 < 6 ? 500 : 5, operatorUtilisation: d % 40 < 6 ? 0.9 : 0.1 } }))
    const times = out.filter((x) => x.d.decision.type === 'hire_operator' || x.d.decision.type === 'fire_operator')
    for (let i = 1; i < times.length; i++) if (times[i]!.d.decision.type !== times[i - 1]!.d.decision.type) expect(times[i]!.day - times[i - 1]!.day).toBeGreaterThan(7)
  })
  it('FX: realised losses widen the volatility buffer (bounded) and calm weeks relax it back', () => {
    const cfg = loadPolicyConfig('baseline')
    const p = new OwnerPolicy()
    let buf = 0.01
    const seq: number[] = []
    for (let day = 0; day < 140; day++) {
      const loss = day < 40 ? -30_000_000 : 0
      for (const d of p.decide(makeObs(day, { fx: { usdtMid: 257_000, dailyVolPct: 1.5, driftPctPerDay: 0.1, realisedFxResultIrt: loss, unrealisedFxResultIrt: 0 }, pricing: { volatilityMinBufferPct: buf, riskBufferPct: 0.005 } }))) {
        if (d.decision.type === 'set_buffers' && d.decision.volatilityMinBufferPct !== undefined) {
          buf = d.decision.volatilityMinBufferPct
          seq.push(buf)
        }
      }
    }
    expect(Math.max(...seq)).toBeLessThanOrEqual(cfg.pricing.fxLossBufferTrigger.maxVolMinBufferPct + 1e-9)
    expect(Math.max(...seq)).toBeGreaterThan(0.01)
    expect(buf).toBeLessThan(Math.max(...seq)) // relaxed afterwards
    expect(buf).toBeGreaterThanOrEqual(0.01 - 1e-9) // never below the baseline
  })
  it('treasury: coverage target follows volatility with a 7-day hysteresis', () => {
    const p = new OwnerPolicy()
    const out = run(p, 30, (d) => makeObs(d, { fx: { usdtMid: 1, dailyVolPct: 4, driftPctPerDay: 0.1, realisedFxResultIrt: 0, unrealisedFxResultIrt: 0 }, treasury: { floatUsdt: 1, coverageDays: 5, targetCoverageDays: 5 } }))
    const cov = out.filter((x) => x.d.decision.type === 'set_target_coverage')
    expect(cov.length).toBeGreaterThanOrEqual(1)
    expect((cov[0]!.d.decision as { days: number }).days).toBe(loadPolicyConfig('baseline').treasury.highVolCoverageDays)
    for (let i = 1; i < cov.length; i++) expect(cov[i]!.day - cov[i - 1]!.day).toBeGreaterThanOrEqual(7)
  })
  it('treasury: capital injection when runway is short — sized, capped monthly, rounded, bounded by owner capital', () => {
    const cfg = loadPolicyConfig('baseline')
    const mk = (d: number, avail?: number) => makeObs(d, { cash: { cashIrt: 100_000_000, burnPerDayIrt: 5_000_000, runwayDays: 20, opexPerMonthIrt: 150_000_000, ownerCapitalAvailableIrt: avail } })
    const p = new OwnerPolicy()
    const out = run(p, 3, (d) => mk(d))
    const inj = out.filter((x) => x.d.decision.type === 'capital_injection')
    expect(inj).toHaveLength(1)
    const amt = (inj[0]!.d.decision as { irt: number }).irt
    expect(amt).toBeLessThanOrEqual(cfg.treasury.maxInjectionPerMonthIrt)
    expect(amt % 1_000_000).toBe(0)
    expect(amt).toBe(Math.min(cfg.treasury.maxInjectionPerMonthIrt, Math.floor((5_000_000 * cfg.treasury.restoreRunwayDays - 100_000_000) / 1e6) * 1e6))
    const limited = new OwnerPolicy()
    const o2 = run(limited, 2, (d) => mk(d, 50_000_000)).filter((x) => x.d.decision.type === 'capital_injection')
    expect((o2[0]!.d.decision as { irt: number }).irt).toBe(50_000_000)
    const none = new OwnerPolicy()
    expect(run(none, 5, (d) => mk(d, 0)).filter((x) => x.d.decision.type === 'capital_injection')).toHaveLength(0)
  })
  it('treasury: monthly owner draw only when rich, profitable and runway is long; never exceeds excess', () => {
    const cfg = loadPolicyConfig('baseline')
    const rich = (d: number) => makeObs(d, { cash: { cashIrt: 2_000_000_000, burnPerDayIrt: 0, runwayDays: Infinity, opexPerMonthIrt: 100_000_000, netProfitLast30dIrt: 50_000_000 } })
    const out = run(new OwnerPolicy(), 70, rich).filter((x) => x.d.decision.type === 'owner_draw')
    expect(out.length).toBeGreaterThanOrEqual(1)
    const excess = 2_000_000_000 - cfg.treasury.drawCashMonthsOfOpexThreshold * 100_000_000
    for (const o of out) expect((o.d.decision as { irt: number }).irt).toBeLessThanOrEqual(excess * cfg.treasury.drawFractionOfExcess)
    const lossy = run(new OwnerPolicy(), 70, (d) => makeObs(d, { cash: { cashIrt: 2e9, burnPerDayIrt: 0, runwayDays: Infinity, opexPerMonthIrt: 1e8, netProfitLast30dIrt: -1 } })).filter((x) => x.d.decision.type === 'owner_draw')
    expect(lossy).toHaveLength(0)
    const poor = run(new OwnerPolicy(), 70, (d) => makeObs(d, { cash: { cashIrt: 2e8, burnPerDayIrt: 0, runwayDays: Infinity, opexPerMonthIrt: 1e8, netProfitLast30dIrt: 5e7 } })).filter((x) => x.d.decision.type === 'owner_draw')
    expect(poor).toHaveLength(0)
  })
  it('marketing: pauses spend when runway is critical; scales with LTV/CAC; mix shifts toward cheaper channels by bounded steps', () => {
    const cfg = loadPolicyConfig('baseline')
    const pause = run(new OwnerPolicy(), 35, (d) => makeObs(d, { cash: { cashIrt: 10_000_000, burnPerDayIrt: 1_000_000, runwayDays: 10, opexPerMonthIrt: 1e8 } })).filter((x) => x.d.decision.type === 'set_marketing_budget')
    expect((pause[0]!.d.decision as { monthlyIrt: number }).monthlyIrt).toBe(0)
    const up = run(new OwnerPolicy(), 35, (d) => makeObs(d, { cash: { cashIrt: 2e9, burnPerDayIrt: 0, runwayDays: Infinity, opexPerMonthIrt: 1e8 }, marketing: { monthlyBudgetIrt: 50_000_000, mix: { seo: 0.5, telegram_channels: 0.5 }, cacByChannel: {}, ltvToCac: 5 } })).filter((x) => x.d.decision.type === 'set_marketing_budget')
    expect((up[0]!.d.decision as { monthlyIrt: number }).monthlyIrt).toBeGreaterThanOrEqual(50_000_000 * cfg.marketing.increaseFactor - 1_000_000)
    const mix = run(new OwnerPolicy(), 35, (d) => makeObs(d, { cash: { cashIrt: 6e8, burnPerDayIrt: 0, runwayDays: Infinity, opexPerMonthIrt: 1e8 }, marketing: { monthlyBudgetIrt: 30_000_000, mix: { seo: 0.5, telegram_channels: 0.5 }, cacByChannel: { seo: 100_000, telegram_channels: 400_000 }, ltvToCac: 2 } })).filter((x) => x.d.decision.type === 'set_marketing_budget')
    const nm = (mix[0]!.d.decision as { mix: Record<string, number> }).mix
    expect(nm.seo).toBeGreaterThan(0.5)
    expect(nm.seo! - 0.5).toBeLessThanOrEqual(cfg.marketing.mixShiftMaxPct + 0.02)
    expect(Object.values(nm).reduce((a, b) => a + b, 0)).toBeCloseTo(1, 3)
  })
  it('providers: switches only after repeated worse observations and respects cooldown', () => {
    const cfg = loadPolicyConfig('baseline')
    const mk = (d: number, fail: number) => makeObs(d, { providers: [{ id: 'mpay', serves: ['virtual_card'], active: ['virtual_card'], failureRate: fail, feeBps: 200 }, { id: 'altcard', serves: ['virtual_card'], active: [], failureRate: 0.01, feeBps: 220 }] })
    const flaky = run(new OwnerPolicy(), 10, (d) => mk(d, 0.2)).filter((x) => x.d.decision.type === 'switch_provider')
    expect(flaky).toHaveLength(1)
    expect(flaky[0]!.day).toBe(cfg.providers.observationsRequired - 1)
    expect((flaky[0]!.d.decision as { providerId: string }).providerId).toBe('altcard')
    const fine = run(new OwnerPolicy(), 10, (d) => mk(d, 0.02)).filter((x) => x.d.decision.type === 'switch_provider')
    expect(fine).toHaveLength(0)
    const blip = run(new OwnerPolicy(), 10, (d) => mk(d, d % 2 === 0 ? 0.2 : 0.01)).filter((x) => x.d.decision.type === 'switch_provider')
    expect(blip).toHaveLength(0)
  })
  it('risk: tightens after a fraud spike and relaxes after calm weeks (hysteresis)', () => {
    const cfg = loadPolicyConfig('baseline')
    const p = new OwnerPolicy()
    let cap = 50_000
    let hold = 70
    const hist: Array<{ day: number; cap: number; hold: number }> = []
    for (let day = 0; day < 140; day++) {
      const rate = day >= 14 && day < 21 ? 0.03 : 0.0005
      for (const d of p.decide(makeObs(day, { kpi: { fraudLossRate: rate }, risk: { newCustomerMaxOrderUsdCents: cap, holdScoreThreshold: hold } }))) {
        if (d.decision.type === 'set_risk_limits') {
          cap = d.decision.newCustomerMaxOrderUsdCents ?? cap
          hold = d.decision.holdScoreThreshold ?? hold
          hist.push({ day, cap, hold })
        }
      }
    }
    expect(hist[0]!.cap).toBeLessThan(50_000)
    expect(hist[0]!.hold).toBeLessThan(70)
    expect(hist[0]!.cap).toBeGreaterThanOrEqual(cfg.risk.minNewCustomerMaxOrderUsdCents)
    expect(hist.length).toBeGreaterThanOrEqual(2)
    expect(hist[hist.length - 1]!.cap).toBeGreaterThan(hist[0]!.cap)
    expect(hist[hist.length - 1]!.cap).toBeLessThanOrEqual(cfg.risk.defaultNewCustomerMaxOrderUsdCents)
  })
  it('kill switch: critical integrity alert ⇒ on once; off only after two clear days', () => {
    const p = new OwnerPolicy()
    const alert = [{ code: 'ledger.imbalance', severity: 'critical' as const, message: 'bad' }]
    const out = run(p, 8, (d) => makeObs(d, { alerts: d >= 1 && d <= 2 ? alert : [] }))
    const ks = out.filter((x) => x.d.decision.type === 'kill_switch')
    expect(ks.map((x) => (x.d.decision as { on: boolean }).on)).toEqual([true, false])
    expect(ks[0]!.day).toBe(1)
    expect(ks[1]!.day).toBe(4)
  })
  it('rush: raises premium when saturated (bounded), eases when idle back to base', () => {
    const cfg = loadPolicyConfig('baseline')
    const p = new OwnerPolicy()
    let prem = 0.2
    const seen: number[] = []
    for (let day = 0; day < 120; day++) {
      const util = day < 60 ? 0.97 : 0.1
      for (const d of p.decide(makeObs(day, { rush: { express: { utilisation: util, queueAgeP90Min: 5, premiumPct: prem } } }))) if (d.decision.type === 'set_rush' && d.decision.premiumPct !== undefined) {
        prem = d.decision.premiumPct
        seen.push(prem)
      }
    }
    expect(Math.max(...seen)).toBeGreaterThan(0.2)
    expect(Math.max(...seen)).toBeLessThanOrEqual(cfg.rush.maxPremiumPct + 1e-9)
    expect(prem).toBeGreaterThanOrEqual(0.2 - 1e-9)
    expect(prem).toBeLessThan(Math.max(...seen))
  })
  it('tax: VAT paid once per quarter in the month after quarter end, capped by cash; income tax once a year', () => {
    const p = new OwnerPolicy()
    const out: PolicyDecision[] = []
    // 1405-07-25 is Mehr 25 (quarter payment month 7)
    for (let day = 0; day < 400; day++) for (const d of p.decide(makeObs(day, { cash: { cashIrt: 1_000_000_000, burnPerDayIrt: 0, runwayDays: Infinity, opexPerMonthIrt: 1e8, vatPayableIrt: 50_000_000, incomeTaxPayableIrt: 20_000_000, netProfitLast30dIrt: 0 } }))) out.push(d)
    const vat = out.filter((d) => d.decision.type === 'pay_tax' && d.decision.kind === 'vat')
    const inc = out.filter((d) => d.decision.type === 'pay_tax' && d.decision.kind === 'income')
    expect(vat.length).toBeGreaterThanOrEqual(3)
    expect(vat.length).toBeLessThanOrEqual(5)
    expect(inc.length).toBeGreaterThanOrEqual(1)
    expect(inc.length).toBeLessThanOrEqual(2)
    const poor = new OwnerPolicy()
    const o2: PolicyDecision[] = []
    for (let day = 0; day < 40; day++) for (const d of poor.decide(makeObs(day, { cash: { cashIrt: 10_000_000, burnPerDayIrt: 0, runwayDays: Infinity, opexPerMonthIrt: 1e8, vatPayableIrt: 50_000_000, netProfitLast30dIrt: 0 } }))) o2.push(d)
    for (const d of o2.filter((x) => x.decision.type === 'pay_tax')) expect((d.decision as { irt: number }).irt).toBeLessThanOrEqual(9_000_000)
  })
  it('presets behave differently on identical input (aggressive injects later, hires later)', () => {
    const mk = (d: number) => makeObs(d, { kpi: { queueAgeP90Min: 400 } })
    const firstHire = (preset: 'conservative' | 'aggressive') => run(new OwnerPolicy({ preset }), 20, mk).find((x) => x.d.decision.type === 'hire_operator')?.day
    expect(firstHire('conservative')!).toBeLessThan(firstHire('aggressive')!)
  })
  it('snapshot/restore reproduces future decisions (replay determinism)', () => {
    const fn = (d: number) => fuzzObs(createRng(1000 + d), d)
    const a = new OwnerPolicy()
    for (let d = 0; d < 20; d++) a.decide(fn(d))
    const snap = a.snapshot()
    const b = new OwnerPolicy()
    b.restore(snap)
    for (let d = 20; d < 60; d++) expect(JSON.stringify(a.decide(fn(d)))).toBe(JSON.stringify(b.decide(fn(d))))
  })
})

describe('policy properties (fuzz)', () => {
  for (const preset of ['conservative', 'baseline', 'aggressive'] as const) {
    it(`${preset}: every decision over 400 random days is schema-valid and within configured bounds`, () => {
      const cfg = loadPolicyConfig(preset)
      const p = new OwnerPolicy({ preset })
      const rng = createRng(7)
      let hires = 0
      let lastMargin: Record<string, number> = {}
      for (let day = 0; day < 400; day++) {
        const obs = fuzzObs(rng, day)
        const ds = p.decide(obs)
        const types = ds.map((d) => d.decision.type)
        expect(types.includes('hire_operator') && types.includes('fire_operator')).toBe(false)
        expect(types.includes('capital_injection') && types.includes('owner_draw')).toBe(false)
        for (const d of ds) {
          const parsed = parseDecisionBody(d.decision)
          expect(parsed.type).toBe(d.decision.type)
          expect(d.rationale.length).toBeGreaterThan(5)
          const x = d.decision
          if (x.type === 'set_margin') {
            const cur = obs.families[x.family]!.marginPct
            expect(x.marginPct).toBeGreaterThanOrEqual(cfg.pricing.floorMarginPct - 1e-9)
            expect(x.marginPct).toBeLessThanOrEqual(Math.max(cfg.pricing.maxMarginPct, cur) + 1e-9)
            expect(Math.abs(x.marginPct - cur)).toBeLessThanOrEqual(cfg.pricing.maxMarginStepPerDecisionPct + 1e-9)
            lastMargin[x.family] = x.marginPct
          }
          if (x.type === 'hire_operator') {
            hires++
            expect(x.count).toBeLessThanOrEqual(cfg.staffing.hireCountPerDecision)
            expect(obs.staff.operators + x.count).toBeLessThanOrEqual(cfg.staffing.maxOperators)
          }
          if (x.type === 'fire_operator') expect(obs.staff.operators).toBeGreaterThan(cfg.staffing.minOperators)
          if (x.type === 'owner_draw') expect(x.irt).toBeLessThanOrEqual(obs.cash.cashIrt)
          if (x.type === 'capital_injection') {
            expect(x.irt).toBeLessThanOrEqual(cfg.treasury.maxInjectionPerMonthIrt)
            if (obs.cash.ownerCapitalAvailableIrt !== undefined) expect(x.irt).toBeLessThanOrEqual(obs.cash.ownerCapitalAvailableIrt)
          }
          if (x.type === 'set_marketing_budget') {
            expect(x.monthlyIrt).toBeLessThanOrEqual(Math.max(cfg.marketing.maxBudgetIrt, obs.marketing.monthlyBudgetIrt))
            if (x.mix) expect(Object.values(x.mix).reduce((a, b) => a + b, 0)).toBeCloseTo(1, 2)
          }
          if (x.type === 'set_target_coverage') expect(x.days).toBeLessThanOrEqual(60)
          if (x.type === 'pay_tax') expect(x.irt).toBeLessThanOrEqual(obs.cash.cashIrt)
          if (x.type === 'set_risk_limits') {
            if (x.holdScoreThreshold !== undefined) {
              expect(x.holdScoreThreshold).toBeGreaterThanOrEqual(cfg.risk.minHoldScore - 1e-9)
              expect(x.holdScoreThreshold).toBeLessThanOrEqual(100)
            }
          }
        }
      }
      expect(hires).toBeGreaterThanOrEqual(0)
      void lastMargin
      lastMargin = {}
    })
  }
  it('is deterministic for identical observation streams', () => {
    const go = () => {
      const p = new OwnerPolicy()
      const rng = createRng(3)
      const out: string[] = []
      for (let d = 0; d < 120; d++) out.push(JSON.stringify(p.decide(fuzzObs(rng, d))))
      return out.join('|')
    }
    expect(go()).toBe(go())
  })
  it('simultaneous days do not break the 30-day window bookkeeping (≥ 1 year run)', () => {
    const p = new OwnerPolicy()
    const rng = createRng(11)
    let n = 0
    for (let d = 0; d < 400; d++) n += p.decide(fuzzObs(rng, d)).length
    expect(n).toBeGreaterThan(20)
    expect(MS.day).toBe(86_400_000)
  })
})
